
package br.gov.sp.saobernardo.paradigma.ws.integracaoporempresa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IPorEmpresa", targetNamespace = "http://tempuri.org/")
public interface IPorEmpresa {


    /**
     * 
     * @param sCdEmpresa
     */
    @WebMethod(operationName = "PreencherEmpresa", action = "http://tempuri.org/IPorEmpresa/PreencherEmpresa")
    @RequestWrapper(localName = "PreencherEmpresa", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.integracaoporempresa.PreencherEmpresa")
    @ResponseWrapper(localName = "PreencherEmpresaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.integracaoporempresa.PreencherEmpresaResponse")
    public void preencherEmpresa(
        @WebParam(name = "sCdEmpresa", targetNamespace = "http://tempuri.org/")
        String sCdEmpresa);

}
