
package br.gov.sp.saobernardo.paradigma.ws.empresagestao;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "EmpresaGestao", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/EmpresaGestao.svc?wsdl")
public class EmpresaGestao
    extends Service
{

    private final static URL EMPRESAGESTAO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.empresagestao.EmpresaGestao.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.empresagestao.EmpresaGestao.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/EmpresaGestao.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/EmpresaGestao.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EMPRESAGESTAO_WSDL_LOCATION = url;
    }

    public EmpresaGestao(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpresaGestao() {
        super(EMPRESAGESTAO_WSDL_LOCATION, new QName("http://tempuri.org/", "EmpresaGestao"));
    }

    /**
     * 
     * @return
     *     returns IEmpresaGestao
     */
    @WebEndpoint(name = "BasicHttpBinding_IEmpresaGestao")
    public IEmpresaGestao getBasicHttpBindingIEmpresaGestao() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEmpresaGestao"), IEmpresaGestao.class);
    }

}
