
package br.gov.sp.saobernardo.paradigma.ws.empresagestao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IEmpresaGestao", targetNamespace = "http://tempuri.org/")
public interface IEmpresaGestao {


    /**
     * 
     * @param lstEmpresaGestao
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresagestao.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarEmpresaGestao", action = "http://tempuri.org/IEmpresaGestao/ProcessarEmpresaGestao")
    @WebResult(name = "ProcessarEmpresaGestaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarEmpresaGestao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresagestao.ProcessarEmpresaGestao")
    @ResponseWrapper(localName = "ProcessarEmpresaGestaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresagestao.ProcessarEmpresaGestaoResponse")
    public RetornoDTO processarEmpresaGestao(
        @WebParam(name = "lstEmpresaGestao", targetNamespace = "http://tempuri.org/")
        ArrayOfEmpresaGestaoDTO lstEmpresaGestao);

}
