
package br.gov.sp.saobernardo.paradigma.ws.pregaoeletronico;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PregaoEletronico", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/PregaoEletronico.svc?wsdl")
public class PregaoEletronico
    extends Service
{

    private final static URL PREGAOELETRONICO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.pregaoeletronico.PregaoEletronico.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.pregaoeletronico.PregaoEletronico.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/PregaoEletronico.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/PregaoEletronico.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PREGAOELETRONICO_WSDL_LOCATION = url;
    }

    public PregaoEletronico(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PregaoEletronico() {
        super(PREGAOELETRONICO_WSDL_LOCATION, new QName("http://tempuri.org/", "PregaoEletronico"));
    }

    /**
     * 
     * @return
     *     returns IPregaoEletronico
     */
    @WebEndpoint(name = "BasicHttpBinding_IPregaoEletronico")
    public IPregaoEletronico getBasicHttpBindingIPregaoEletronico() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPregaoEletronico"), IPregaoEletronico.class);
    }

}
