
package br.gov.sp.saobernardo.paradigma.ws.ordemcompra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IOrdemCompra", targetNamespace = "http://tempuri.org/")
public interface IOrdemCompra {


    /**
     * 
     * @param nCdTipoOrdemCompra
     * @param nQtRegistros
     * @param sCdOrdemCompraEmpresa
     * @param nCdOrdemCompra
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.ordemcompra.RetornoListaX003COrdemCompraDTOX003E
     */
    @WebMethod(operationName = "RetornarOrdemCompra", action = "http://tempuri.org/IOrdemCompra/RetornarOrdemCompra")
    @WebResult(name = "RetornarOrdemCompraResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarOrdemCompra", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.ordemcompra.RetornarOrdemCompra")
    @ResponseWrapper(localName = "RetornarOrdemCompraResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.ordemcompra.RetornarOrdemCompraResponse")
    public RetornoListaX003COrdemCompraDTOX003E retornarOrdemCompra(
        @WebParam(name = "nQtRegistros", targetNamespace = "http://tempuri.org/")
        Integer nQtRegistros,
        @WebParam(name = "nCdTipoOrdemCompra", targetNamespace = "http://tempuri.org/")
        Integer nCdTipoOrdemCompra,
        @WebParam(name = "nCdOrdemCompra", targetNamespace = "http://tempuri.org/")
        Integer nCdOrdemCompra,
        @WebParam(name = "sCdOrdemCompraEmpresa", targetNamespace = "http://tempuri.org/")
        String sCdOrdemCompraEmpresa);

    /**
     * 
     * @param nCdTipoOrdemCompra
     * @param nQtRegistros
     * @param nCdOrdemCompra
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.ordemcompra.RetornoListaX003COrdemCompraConsumoDTOX003E
     */
    @WebMethod(operationName = "RetornarOrdemCompraConsumo", action = "http://tempuri.org/IOrdemCompra/RetornarOrdemCompraConsumo")
    @WebResult(name = "RetornarOrdemCompraConsumoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarOrdemCompraConsumo", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.ordemcompra.RetornarOrdemCompraConsumo")
    @ResponseWrapper(localName = "RetornarOrdemCompraConsumoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.ordemcompra.RetornarOrdemCompraConsumoResponse")
    public RetornoListaX003COrdemCompraConsumoDTOX003E retornarOrdemCompraConsumo(
        @WebParam(name = "nQtRegistros", targetNamespace = "http://tempuri.org/")
        Integer nQtRegistros,
        @WebParam(name = "nCdTipoOrdemCompra", targetNamespace = "http://tempuri.org/")
        Integer nCdTipoOrdemCompra,
        @WebParam(name = "nCdOrdemCompra", targetNamespace = "http://tempuri.org/")
        Integer nCdOrdemCompra);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.ordemcompra.RetornoListaX003COrdemCompraTipoDTOX003E
     */
    @WebMethod(operationName = "RetornarOrdemCompraTipo", action = "http://tempuri.org/IOrdemCompra/RetornarOrdemCompraTipo")
    @WebResult(name = "RetornarOrdemCompraTipoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarOrdemCompraTipo", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.ordemcompra.RetornarOrdemCompraTipo")
    @ResponseWrapper(localName = "RetornarOrdemCompraTipoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.ordemcompra.RetornarOrdemCompraTipoResponse")
    public RetornoListaX003COrdemCompraTipoDTOX003E retornarOrdemCompraTipo();

    /**
     * 
     * @param lstOrdemCompra
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.ordemcompra.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarOrdemCompra", action = "http://tempuri.org/IOrdemCompra/ProcessarOrdemCompra")
    @WebResult(name = "ProcessarOrdemCompraResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarOrdemCompra", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.ordemcompra.ProcessarOrdemCompra")
    @ResponseWrapper(localName = "ProcessarOrdemCompraResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.ordemcompra.ProcessarOrdemCompraResponse")
    public RetornoDTO processarOrdemCompra(
        @WebParam(name = "lstOrdemCompra", targetNamespace = "http://tempuri.org/")
        ArrayOfOrdemCompraDTO lstOrdemCompra);

}
