
package br.gov.sp.saobernardo.paradigma.ws.contrato;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Contrato", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Contrato.svc?wsdl")
public class Contrato
    extends Service
{

    private final static URL CONTRATO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.contrato.Contrato.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.contrato.Contrato.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Contrato.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Contrato.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONTRATO_WSDL_LOCATION = url;
    }

    public Contrato(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Contrato() {
        super(CONTRATO_WSDL_LOCATION, new QName("http://tempuri.org/", "Contrato"));
    }

    /**
     * 
     * @return
     *     returns IContrato
     */
    @WebEndpoint(name = "BasicHttpBinding_IContrato")
    public IContrato getBasicHttpBindingIContrato() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IContrato"), IContrato.class);
    }

}
