
package br.gov.sp.saobernardo.paradigma.ws.contrato;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IContrato", targetNamespace = "http://tempuri.org/")
public interface IContrato {


    /**
     * 
     * @param lstContrato
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarContrato", action = "http://tempuri.org/IContrato/ProcessarContrato")
    @WebResult(name = "ProcessarContratoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarContrato", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.ProcessarContrato")
    @ResponseWrapper(localName = "ProcessarContratoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.ProcessarContratoResponse")
    public RetornoDTO processarContrato(
        @WebParam(name = "lstContrato", targetNamespace = "http://tempuri.org/")
        ArrayOfContratoDTO lstContrato);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoCotacao", action = "http://tempuri.org/IContrato/RetornarContratoCotacao")
    @WebResult(name = "RetornarContratoCotacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoCotacao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoCotacao")
    @ResponseWrapper(localName = "RetornarContratoCotacaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoCotacaoResponse")
    public ArrayOfContratoDTO retornarContratoCotacao();

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoLeilao", action = "http://tempuri.org/IContrato/RetornarContratoLeilao")
    @WebResult(name = "RetornarContratoLeilaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoLeilao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoLeilao")
    @ResponseWrapper(localName = "RetornarContratoLeilaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoLeilaoResponse")
    public ArrayOfContratoDTO retornarContratoLeilao();

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoAtivo", action = "http://tempuri.org/IContrato/RetornarContratoAtivo")
    @WebResult(name = "RetornarContratoAtivoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoAtivo", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoAtivo")
    @ResponseWrapper(localName = "RetornarContratoAtivoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoAtivoResponse")
    public ArrayOfContratoDTO retornarContratoAtivo();

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoRescindido", action = "http://tempuri.org/IContrato/RetornarContratoRescindido")
    @WebResult(name = "RetornarContratoRescindidoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoRescindido", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoRescindido")
    @ResponseWrapper(localName = "RetornarContratoRescindidoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoRescindidoResponse")
    public ArrayOfContratoDTO retornarContratoRescindido();

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoPorTermoAditivo", action = "http://tempuri.org/IContrato/RetornarContratoPorTermoAditivo")
    @WebResult(name = "RetornarContratoPorTermoAditivoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoPorTermoAditivo", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorTermoAditivo")
    @ResponseWrapper(localName = "RetornarContratoPorTermoAditivoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorTermoAditivoResponse")
    public ArrayOfContratoDTO retornarContratoPorTermoAditivo();

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoEncerrado", action = "http://tempuri.org/IContrato/RetornarContratoEncerrado")
    @WebResult(name = "RetornarContratoEncerradoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoEncerrado", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoEncerrado")
    @ResponseWrapper(localName = "RetornarContratoEncerradoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoEncerradoResponse")
    public ArrayOfContratoDTO retornarContratoEncerrado();

    /**
     * 
     * @param sCdEmpresaContratante
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoPorComprador", action = "http://tempuri.org/IContrato/RetornarContratoPorComprador")
    @WebResult(name = "RetornarContratoPorCompradorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoPorComprador", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorComprador")
    @ResponseWrapper(localName = "RetornarContratoPorCompradorResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorCompradorResponse")
    public ArrayOfContratoDTO retornarContratoPorComprador(
        @WebParam(name = "sCdEmpresaContratante", targetNamespace = "http://tempuri.org/")
        String sCdEmpresaContratante);

    /**
     * 
     * @param sCdEmpresaFornecedor
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoPorFornecedor", action = "http://tempuri.org/IContrato/RetornarContratoPorFornecedor")
    @WebResult(name = "RetornarContratoPorFornecedorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoPorFornecedor", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorFornecedor")
    @ResponseWrapper(localName = "RetornarContratoPorFornecedorResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorFornecedorResponse")
    public ArrayOfContratoDTO retornarContratoPorFornecedor(
        @WebParam(name = "sCdEmpresaFornecedor", targetNamespace = "http://tempuri.org/")
        String sCdEmpresaFornecedor);

    /**
     * 
     * @param sCdProduto
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoPorItem", action = "http://tempuri.org/IContrato/RetornarContratoPorItem")
    @WebResult(name = "RetornarContratoPorItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoPorItem", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorItem")
    @ResponseWrapper(localName = "RetornarContratoPorItemResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorItemResponse")
    public ArrayOfContratoDTO retornarContratoPorItem(
        @WebParam(name = "sCdProduto", targetNamespace = "http://tempuri.org/")
        String sCdProduto);

    /**
     * 
     * @param oContratoPesquisaDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoPorCompradorItem", action = "http://tempuri.org/IContrato/RetornarContratoPorCompradorItem")
    @WebResult(name = "RetornarContratoPorCompradorItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoPorCompradorItem", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorCompradorItem")
    @ResponseWrapper(localName = "RetornarContratoPorCompradorItemResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorCompradorItemResponse")
    public ArrayOfContratoDTO retornarContratoPorCompradorItem(
        @WebParam(name = "oContratoPesquisaDTO", targetNamespace = "http://tempuri.org/")
        ContratoPesquisaDTO oContratoPesquisaDTO);

    /**
     * 
     * @param oContratoPesquisaDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contrato.ArrayOfContratoDTO
     */
    @WebMethod(operationName = "RetornarContratoPorFornecedorItem", action = "http://tempuri.org/IContrato/RetornarContratoPorFornecedorItem")
    @WebResult(name = "RetornarContratoPorFornecedorItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarContratoPorFornecedorItem", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorFornecedorItem")
    @ResponseWrapper(localName = "RetornarContratoPorFornecedorItemResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarContratoPorFornecedorItemResponse")
    public ArrayOfContratoDTO retornarContratoPorFornecedorItem(
        @WebParam(name = "oContratoPesquisaDTO", targetNamespace = "http://tempuri.org/")
        ContratoPesquisaDTO oContratoPesquisaDTO);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornarCodigoContratoSequencia", action = "http://tempuri.org/IContrato/RetornarCodigoContratoSequencia")
    @WebResult(name = "RetornarCodigoContratoSequenciaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarCodigoContratoSequencia", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarCodigoContratoSequencia")
    @ResponseWrapper(localName = "RetornarCodigoContratoSequenciaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contrato.RetornarCodigoContratoSequenciaResponse")
    public String retornarCodigoContratoSequencia();

}
