
package br.gov.sp.saobernardo.paradigma.ws.moedacotacao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IMoedaCotacao", targetNamespace = "http://tempuri.org/")
public interface IMoedaCotacao {


    /**
     * 
     * @param lstMoedaCotacao
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.moedacotacao.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarMoedaCotacao", action = "http://tempuri.org/IMoedaCotacao/ProcessarMoedaCotacao")
    @WebResult(name = "ProcessarMoedaCotacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarMoedaCotacao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.moedacotacao.ProcessarMoedaCotacao")
    @ResponseWrapper(localName = "ProcessarMoedaCotacaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.moedacotacao.ProcessarMoedaCotacaoResponse")
    public RetornoDTO processarMoedaCotacao(
        @WebParam(name = "lstMoedaCotacao", targetNamespace = "http://tempuri.org/")
        ArrayOfMoedaCotacaoDTO lstMoedaCotacao);

}
