
package br.gov.sp.saobernardo.paradigma.ws.erro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IRetornoLog", targetNamespace = "http://tempuri.org/")
public interface IRetornoLog {


    /**
     * 
     * @param nCdOperacao
     * @param sDsLog
     * @param sDsLogDetalhado
     */
    @WebMethod(operationName = "ProcessarErro", action = "http://tempuri.org/IRetornoLog/ProcessarErro")
    @RequestWrapper(localName = "ProcessarErro", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.erro.ProcessarErro")
    @ResponseWrapper(localName = "ProcessarErroResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.erro.ProcessarErroResponse")
    public void processarErro(
        @WebParam(name = "nCdOperacao", targetNamespace = "http://tempuri.org/")
        Integer nCdOperacao,
        @WebParam(name = "sDsLog", targetNamespace = "http://tempuri.org/")
        String sDsLog,
        @WebParam(name = "sDsLogDetalhado", targetNamespace = "http://tempuri.org/")
        String sDsLogDetalhado);

    /**
     * 
     * @param sNrToken
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.erro.RetornoDTO
     */
    @WebMethod(operationName = "RetornarErro", action = "http://tempuri.org/IRetornoLog/RetornarErro")
    @WebResult(name = "RetornarErroResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarErro", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.erro.RetornarErro")
    @ResponseWrapper(localName = "RetornarErroResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.erro.RetornarErroResponse")
    public RetornoDTO retornarErro(
        @WebParam(name = "sNrToken", targetNamespace = "http://tempuri.org/")
        String sNrToken);

    /**
     * 
     * @param sNrToken
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.erro.RetornoDTO
     */
    @WebMethod(operationName = "RetornarSucesso", action = "http://tempuri.org/IRetornoLog/RetornarSucesso")
    @WebResult(name = "RetornarSucessoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarSucesso", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.erro.RetornarSucesso")
    @ResponseWrapper(localName = "RetornarSucessoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.erro.RetornarSucessoResponse")
    public RetornoDTO retornarSucesso(
        @WebParam(name = "sNrToken", targetNamespace = "http://tempuri.org/")
        String sNrToken);

    /**
     * 
     * @param sNrToken
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.erro.RetornoDTO
     */
    @WebMethod(operationName = "RetornarLog", action = "http://tempuri.org/IRetornoLog/RetornarLog")
    @WebResult(name = "RetornarLogResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarLog", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.erro.RetornarLog")
    @ResponseWrapper(localName = "RetornarLogResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.erro.RetornarLogResponse")
    public RetornoDTO retornarLog(
        @WebParam(name = "sNrToken", targetNamespace = "http://tempuri.org/")
        String sNrToken);

}
