
package br.gov.sp.saobernardo.paradigma.ws.erro;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "RetornoLog", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Erro.svc?wsdl")
public class RetornoLog
    extends Service
{

    private final static URL RETORNOLOG_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.erro.RetornoLog.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.erro.RetornoLog.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Erro.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Erro.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RETORNOLOG_WSDL_LOCATION = url;
    }

    public RetornoLog(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RetornoLog() {
        super(RETORNOLOG_WSDL_LOCATION, new QName("http://tempuri.org/", "RetornoLog"));
    }

    /**
     * 
     * @return
     *     returns IRetornoLog
     */
    @WebEndpoint(name = "BasicHttpBinding_IRetornoLog")
    public IRetornoLog getBasicHttpBindingIRetornoLog() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IRetornoLog"), IRetornoLog.class);
    }

}
