
package br.gov.sp.saobernardo.paradigma.ws.empenho;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Empenho", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Empenho.svc?wsdl")
public class Empenho
    extends Service
{

    private final static URL EMPENHO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.empenho.Empenho.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.empenho.Empenho.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Empenho.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Empenho.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EMPENHO_WSDL_LOCATION = url;
    }

    public Empenho(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Empenho() {
        super(EMPENHO_WSDL_LOCATION, new QName("http://tempuri.org/", "Empenho"));
    }

    /**
     * 
     * @return
     *     returns IEmpenho
     */
    @WebEndpoint(name = "BasicHttpBinding_IEmpenho")
    public IEmpenho getBasicHttpBindingIEmpenho() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEmpenho"), IEmpenho.class);
    }

}
