
package br.gov.sp.saobernardo.paradigma.ws.empenho;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IEmpenho", targetNamespace = "http://tempuri.org/")
public interface IEmpenho {


    /**
     * 
     * @param lstEmpenhoCapa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empenho.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarEmpenho", action = "http://tempuri.org/IEmpenho/ProcessarEmpenho")
    @WebResult(name = "ProcessarEmpenhoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarEmpenho", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarEmpenho")
    @ResponseWrapper(localName = "ProcessarEmpenhoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarEmpenhoResponse")
    public RetornoDTO processarEmpenho(
        @WebParam(name = "lstEmpenhoCapa", targetNamespace = "http://tempuri.org/")
        ArrayOfEmpenhoCapaDTO lstEmpenhoCapa);

    /**
     * 
     * @param lstEmpenhoItemCapaDto
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empenho.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarEmpenhoItem", action = "http://tempuri.org/IEmpenho/ProcessarEmpenhoItem")
    @WebResult(name = "ProcessarEmpenhoItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarEmpenhoItem", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarEmpenhoItem")
    @ResponseWrapper(localName = "ProcessarEmpenhoItemResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarEmpenhoItemResponse")
    public RetornoDTO processarEmpenhoItem(
        @WebParam(name = "lstEmpenhoItemCapaDto", targetNamespace = "http://tempuri.org/")
        ArrayOfEmpenhoItemCapaDTO lstEmpenhoItemCapaDto);

    /**
     * 
     * @param lstLiquidacaoEmpenhoDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empenho.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarLiquidacaoEmpenho", action = "http://tempuri.org/IEmpenho/ProcessarLiquidacaoEmpenho")
    @WebResult(name = "ProcessarLiquidacaoEmpenhoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarLiquidacaoEmpenho", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarLiquidacaoEmpenho")
    @ResponseWrapper(localName = "ProcessarLiquidacaoEmpenhoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarLiquidacaoEmpenhoResponse")
    public RetornoDTO processarLiquidacaoEmpenho(
        @WebParam(name = "lstLiquidacaoEmpenhoDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfLiquidacaoEmpenhoDTO lstLiquidacaoEmpenhoDTO);

    /**
     * 
     * @param lstLiquidacaoEmpenhoItemDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empenho.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarLiquidacaoEmpenhoItem", action = "http://tempuri.org/IEmpenho/ProcessarLiquidacaoEmpenhoItem")
    @WebResult(name = "ProcessarLiquidacaoEmpenhoItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarLiquidacaoEmpenhoItem", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarLiquidacaoEmpenhoItem")
    @ResponseWrapper(localName = "ProcessarLiquidacaoEmpenhoItemResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarLiquidacaoEmpenhoItemResponse")
    public RetornoDTO processarLiquidacaoEmpenhoItem(
        @WebParam(name = "lstLiquidacaoEmpenhoItemDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfLiquidacaoEmpenhoItemDTO lstLiquidacaoEmpenhoItemDTO);

    /**
     * 
     * @param lstLiquidacaoEmpenhoDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empenho.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarEstornoEmpenho", action = "http://tempuri.org/IEmpenho/ProcessarEstornoEmpenho")
    @WebResult(name = "ProcessarEstornoEmpenhoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarEstornoEmpenho", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarEstornoEmpenho")
    @ResponseWrapper(localName = "ProcessarEstornoEmpenhoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarEstornoEmpenhoResponse")
    public RetornoDTO processarEstornoEmpenho(
        @WebParam(name = "lstLiquidacaoEmpenhoDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfLiquidacaoEmpenhoDTO lstLiquidacaoEmpenhoDTO);

    /**
     * 
     * @param lstLiquidacaoEmpenhoItemDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empenho.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarEstornoEmpenhoItem", action = "http://tempuri.org/IEmpenho/ProcessarEstornoEmpenhoItem")
    @WebResult(name = "ProcessarEstornoEmpenhoItemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarEstornoEmpenhoItem", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarEstornoEmpenhoItem")
    @ResponseWrapper(localName = "ProcessarEstornoEmpenhoItemResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarEstornoEmpenhoItemResponse")
    public RetornoDTO processarEstornoEmpenhoItem(
        @WebParam(name = "lstLiquidacaoEmpenhoItemDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfLiquidacaoEmpenhoItemDTO lstLiquidacaoEmpenhoItemDTO);

    /**
     * 
     * @param lstEmpenhoDesembolsoDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empenho.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarDesembolsoEmpenho", action = "http://tempuri.org/IEmpenho/ProcessarDesembolsoEmpenho")
    @WebResult(name = "ProcessarDesembolsoEmpenhoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarDesembolsoEmpenho", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarDesembolsoEmpenho")
    @ResponseWrapper(localName = "ProcessarDesembolsoEmpenhoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empenho.ProcessarDesembolsoEmpenhoResponse")
    public RetornoDTO processarDesembolsoEmpenho(
        @WebParam(name = "lstEmpenhoDesembolsoDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfEmpenhoDesembolsoDTO lstEmpenhoDesembolsoDTO);

}
