
package br.gov.sp.saobernardo.paradigma.ws.cfop;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Cfop", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Cfop.svc?wsdl")
public class Cfop
    extends Service
{

    private final static URL CFOP_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.cfop.Cfop.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.cfop.Cfop.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Cfop.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Cfop.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CFOP_WSDL_LOCATION = url;
    }

    public Cfop(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Cfop() {
        super(CFOP_WSDL_LOCATION, new QName("http://tempuri.org/", "Cfop"));
    }

    /**
     * 
     * @return
     *     returns ICfop
     */
    @WebEndpoint(name = "BasicHttpBinding_ICfop")
    public ICfop getBasicHttpBindingICfop() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICfop"), ICfop.class);
    }

}
