
package br.gov.sp.saobernardo.paradigma.ws.aplicacao;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Aplicacao", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Aplicacao.svc?wsdl")
public class Aplicacao
    extends Service
{

    private final static URL APLICACAO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.aplicacao.Aplicacao.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.aplicacao.Aplicacao.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Aplicacao.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Aplicacao.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        APLICACAO_WSDL_LOCATION = url;
    }

    public Aplicacao(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Aplicacao() {
        super(APLICACAO_WSDL_LOCATION, new QName("http://tempuri.org/", "Aplicacao"));
    }

    /**
     * 
     * @return
     *     returns IAplicacao
     */
    @WebEndpoint(name = "BasicHttpBinding_IAplicacao")
    public IAplicacao getBasicHttpBindingIAplicacao() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAplicacao"), IAplicacao.class);
    }

}
