
package br.gov.sp.saobernardo.paradigma.ws.aplicacao;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IAplicacao", targetNamespace = "http://tempuri.org/")
public interface IAplicacao {


    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.aplicacao.RetornoListaX003CAplicacaoDTOX003E
     */
    @WebMethod(operationName = "RetornarAplicacao", action = "http://tempuri.org/IAplicacao/RetornarAplicacao")
    @WebResult(name = "RetornarAplicacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarAplicacao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.aplicacao.RetornarAplicacao")
    @ResponseWrapper(localName = "RetornarAplicacaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.aplicacao.RetornarAplicacaoResponse")
    public RetornoListaX003CAplicacaoDTOX003E retornarAplicacao();

}
