
package br.gov.sp.saobernardo.paradigma.ws.moeda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IMoeda", targetNamespace = "http://tempuri.org/")
public interface IMoeda {


    /**
     * 
     * @param lstMoeda
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.moeda.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarMoeda", action = "http://tempuri.org/IMoeda/ProcessarMoeda")
    @WebResult(name = "ProcessarMoedaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarMoeda", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.moeda.ProcessarMoeda")
    @ResponseWrapper(localName = "ProcessarMoedaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.moeda.ProcessarMoedaResponse")
    public RetornoDTO processarMoeda(
        @WebParam(name = "lstMoeda", targetNamespace = "http://tempuri.org/")
        ArrayOfMoedaDTO lstMoeda);

}
