
package br.gov.sp.saobernardo.paradigma.ws.contacontabil;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ContaContabil", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/ContaContabil.svc?wsdl")
public class ContaContabil
    extends Service
{

    private final static URL CONTACONTABIL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.contacontabil.ContaContabil.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.contacontabil.ContaContabil.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/ContaContabil.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/ContaContabil.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONTACONTABIL_WSDL_LOCATION = url;
    }

    public ContaContabil(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContaContabil() {
        super(CONTACONTABIL_WSDL_LOCATION, new QName("http://tempuri.org/", "ContaContabil"));
    }

    /**
     * 
     * @return
     *     returns IContaContabil
     */
    @WebEndpoint(name = "BasicHttpBinding_IContaContabil")
    public IContaContabil getBasicHttpBindingIContaContabil() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IContaContabil"), IContaContabil.class);
    }

}
