
package br.gov.sp.saobernardo.paradigma.ws.contacontabil;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IContaContabil", targetNamespace = "http://tempuri.org/")
public interface IContaContabil {


    /**
     * 
     * @param lstContaContabil
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.contacontabil.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarContaContabil", action = "http://tempuri.org/IContaContabil/ProcessarContaContabil")
    @WebResult(name = "ProcessarContaContabilResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarContaContabil", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contacontabil.ProcessarContaContabil")
    @ResponseWrapper(localName = "ProcessarContaContabilResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.contacontabil.ProcessarContaContabilResponse")
    public RetornoDTO processarContaContabil(
        @WebParam(name = "lstContaContabil", targetNamespace = "http://tempuri.org/")
        ArrayOfContaContabilDTO lstContaContabil);

}
