
package br.gov.sp.saobernardo.paradigma.ws.fonterecurso;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "FonteRecurso", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/FonteRecurso.svc?wsdl")
public class FonteRecurso
    extends Service
{

    private final static URL FONTERECURSO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.fonterecurso.FonteRecurso.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.fonterecurso.FonteRecurso.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/FonteRecurso.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/FonteRecurso.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FONTERECURSO_WSDL_LOCATION = url;
    }

    public FonteRecurso(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FonteRecurso() {
        super(FONTERECURSO_WSDL_LOCATION, new QName("http://tempuri.org/", "FonteRecurso"));
    }

    /**
     * 
     * @return
     *     returns IFonteRecurso
     */
    @WebEndpoint(name = "BasicHttpBinding_IFonteRecurso")
    public IFonteRecurso getBasicHttpBindingIFonteRecurso() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IFonteRecurso"), IFonteRecurso.class);
    }

}
