
package br.gov.sp.saobernardo.paradigma.ws.fonterecurso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IFonteRecurso", targetNamespace = "http://tempuri.org/")
public interface IFonteRecurso {


    /**
     * 
     * @param lstFonteRecurso
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.fonterecurso.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarFonteRecurso", action = "http://tempuri.org/IFonteRecurso/ProcessarFonteRecurso")
    @WebResult(name = "ProcessarFonteRecursoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarFonteRecurso", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.fonterecurso.ProcessarFonteRecurso")
    @ResponseWrapper(localName = "ProcessarFonteRecursoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.fonterecurso.ProcessarFonteRecursoResponse")
    public RetornoDTO processarFonteRecurso(
        @WebParam(name = "lstFonteRecurso", targetNamespace = "http://tempuri.org/")
        ArrayOfFonteRecursoDTO lstFonteRecurso);

}
