
package br.gov.sp.saobernardo.paradigma.ws.prioridade;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IPrioridade", targetNamespace = "http://tempuri.org/")
public interface IPrioridade {


    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.prioridade.RetornoListaX003CPrioridadeDTOX003E
     */
    @WebMethod(operationName = "RetornarPrioridade", action = "http://tempuri.org/IPrioridade/RetornarPrioridade")
    @WebResult(name = "RetornarPrioridadeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarPrioridade", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.prioridade.RetornarPrioridade")
    @ResponseWrapper(localName = "RetornarPrioridadeResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.prioridade.RetornarPrioridadeResponse")
    public RetornoListaX003CPrioridadeDTOX003E retornarPrioridade();

}
