
package br.gov.sp.saobernardo.paradigma.ws.prioridade;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Prioridade", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Prioridade.svc?wsdl")
public class Prioridade
    extends Service
{

    private final static URL PRIORIDADE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.prioridade.Prioridade.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.prioridade.Prioridade.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Prioridade.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Prioridade.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PRIORIDADE_WSDL_LOCATION = url;
    }

    public Prioridade(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Prioridade() {
        super(PRIORIDADE_WSDL_LOCATION, new QName("http://tempuri.org/", "Prioridade"));
    }

    /**
     * 
     * @return
     *     returns IPrioridade
     */
    @WebEndpoint(name = "BasicHttpBinding_IPrioridade")
    public IPrioridade getBasicHttpBindingIPrioridade() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPrioridade"), IPrioridade.class);
    }

}
