
package br.gov.sp.saobernardo.paradigma.ws.empresacondicaopagamento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IEmpresaCondicaoPagamento", targetNamespace = "http://tempuri.org/")
public interface IEmpresaCondicaoPagamento {


    /**
     * 
     * @param lstEmpresaCondicaoPagamento
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresacondicaopagamento.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarEmpresaCondicaoPagamento", action = "http://tempuri.org/IEmpresaCondicaoPagamento/ProcessarEmpresaCondicaoPagamento")
    @WebResult(name = "ProcessarEmpresaCondicaoPagamentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarEmpresaCondicaoPagamento", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresacondicaopagamento.ProcessarEmpresaCondicaoPagamento")
    @ResponseWrapper(localName = "ProcessarEmpresaCondicaoPagamentoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresacondicaopagamento.ProcessarEmpresaCondicaoPagamentoResponse")
    public RetornoDTO processarEmpresaCondicaoPagamento(
        @WebParam(name = "lstEmpresaCondicaoPagamento", targetNamespace = "http://tempuri.org/")
        ArrayOfEmpresaCondicaoPagamentoDTO lstEmpresaCondicaoPagamento);

}
