
package br.gov.sp.saobernardo.paradigma.ws.usuario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IUsuario", targetNamespace = "http://tempuri.org/")
public interface IUsuario {


    /**
     * 
     * @param lstUsuario
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.usuario.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarUsuario", action = "http://tempuri.org/IUsuario/ProcessarUsuario")
    @WebResult(name = "ProcessarUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarUsuario", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.usuario.ProcessarUsuario")
    @ResponseWrapper(localName = "ProcessarUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.usuario.ProcessarUsuarioResponse")
    public RetornoDTO processarUsuario(
        @WebParam(name = "lstUsuario", targetNamespace = "http://tempuri.org/")
        ArrayOfUsuarioDTO lstUsuario);

    /**
     * 
     * @param sCdUsuario
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.usuario.UsuarioDTO
     */
    @WebMethod(operationName = "RetornarUsuario", action = "http://tempuri.org/IUsuario/RetornarUsuario")
    @WebResult(name = "RetornarUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarUsuario", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.usuario.RetornarUsuario")
    @ResponseWrapper(localName = "RetornarUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.usuario.RetornarUsuarioResponse")
    public UsuarioDTO retornarUsuario(
        @WebParam(name = "sCdUsuario", targetNamespace = "http://tempuri.org/")
        String sCdUsuario);

    /**
     * 
     * @param sCdEmpresa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.usuario.RetornoListaX003CUsuarioDTOX003E
     */
    @WebMethod(operationName = "RetornarUsuarioPorEmpresa", action = "http://tempuri.org/IUsuario/RetornarUsuarioPorEmpresa")
    @WebResult(name = "RetornarUsuarioPorEmpresaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarUsuarioPorEmpresa", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.usuario.RetornarUsuarioPorEmpresa")
    @ResponseWrapper(localName = "RetornarUsuarioPorEmpresaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.usuario.RetornarUsuarioPorEmpresaResponse")
    public RetornoListaX003CUsuarioDTOX003E retornarUsuarioPorEmpresa(
        @WebParam(name = "sCdEmpresa", targetNamespace = "http://tempuri.org/")
        String sCdEmpresa);

    /**
     * 
     * @param sLstCdStUsuario
     * @param sCdEmpresa
     * @param nNrPagina
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.usuario.RetornoListaX003CUsuarioDTOX003E
     */
    @WebMethod(operationName = "RetornarUsuarioComprador", action = "http://tempuri.org/IUsuario/RetornarUsuarioComprador")
    @WebResult(name = "RetornarUsuarioCompradorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarUsuarioComprador", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.usuario.RetornarUsuarioComprador")
    @ResponseWrapper(localName = "RetornarUsuarioCompradorResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.usuario.RetornarUsuarioCompradorResponse")
    public RetornoListaX003CUsuarioDTOX003E retornarUsuarioComprador(
        @WebParam(name = "sCdEmpresa", targetNamespace = "http://tempuri.org/")
        String sCdEmpresa,
        @WebParam(name = "sLstCdStUsuario", targetNamespace = "http://tempuri.org/")
        String sLstCdStUsuario,
        @WebParam(name = "nNrPagina", targetNamespace = "http://tempuri.org/")
        Integer nNrPagina);

    /**
     * 
     * @param lstSituacaoUsuario
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.usuario.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarUsuarioSituacao", action = "http://tempuri.org/IUsuario/ProcessarUsuarioSituacao")
    @WebResult(name = "ProcessarUsuarioSituacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarUsuarioSituacao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.usuario.ProcessarUsuarioSituacao")
    @ResponseWrapper(localName = "ProcessarUsuarioSituacaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.usuario.ProcessarUsuarioSituacaoResponse")
    public RetornoDTO processarUsuarioSituacao(
        @WebParam(name = "lstSituacaoUsuario", targetNamespace = "http://tempuri.org/")
        ArrayOfUsuarioSituacaoDTO lstSituacaoUsuario);

}
