
package br.gov.sp.saobernardo.paradigma.ws.usuario;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Usuario", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Usuario.svc?wsdl")
public class Usuario
    extends Service
{

    private final static URL USUARIO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.usuario.Usuario.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.usuario.Usuario.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Usuario.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Usuario.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USUARIO_WSDL_LOCATION = url;
    }

    public Usuario(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Usuario() {
        super(USUARIO_WSDL_LOCATION, new QName("http://tempuri.org/", "Usuario"));
    }

    /**
     * 
     * @return
     *     returns IUsuario
     */
    @WebEndpoint(name = "BasicHttpBinding_IUsuario")
    public IUsuario getBasicHttpBindingIUsuario() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IUsuario"), IUsuario.class);
    }

}
