
package br.gov.sp.saobernardo.paradigma.ws.titulo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ITitulo", targetNamespace = "http://tempuri.org/")
public interface ITitulo {


    /**
     * 
     * @param lstTitulo
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.titulo.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarTitulo", action = "http://tempuri.org/ITitulo/ProcessarTitulo")
    @WebResult(name = "ProcessarTituloResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarTitulo", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.titulo.ProcessarTitulo")
    @ResponseWrapper(localName = "ProcessarTituloResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.titulo.ProcessarTituloResponse")
    public RetornoDTO processarTitulo(
        @WebParam(name = "lstTitulo", targetNamespace = "http://tempuri.org/")
        ArrayOfTituloDTO lstTitulo);

}
