
package br.gov.sp.saobernardo.paradigma.ws.titulo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Titulo", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Titulo.svc?wsdl")
public class Titulo
    extends Service
{

    private final static URL TITULO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.titulo.Titulo.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.titulo.Titulo.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Titulo.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Titulo.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TITULO_WSDL_LOCATION = url;
    }

    public Titulo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Titulo() {
        super(TITULO_WSDL_LOCATION, new QName("http://tempuri.org/", "Titulo"));
    }

    /**
     * 
     * @return
     *     returns ITitulo
     */
    @WebEndpoint(name = "BasicHttpBinding_ITitulo")
    public ITitulo getBasicHttpBindingITitulo() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ITitulo"), ITitulo.class);
    }

}
