
package br.gov.sp.saobernardo.paradigma.ws.iva;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IIva", targetNamespace = "http://tempuri.org/")
public interface IIva {


    /**
     * 
     * @param lstIva
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.iva.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarIva", action = "http://tempuri.org/IIva/ProcessarIva")
    @WebResult(name = "ProcessarIvaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarIva", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.iva.ProcessarIva")
    @ResponseWrapper(localName = "ProcessarIvaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.iva.ProcessarIvaResponse")
    public RetornoDTO processarIva(
        @WebParam(name = "lstIva", targetNamespace = "http://tempuri.org/")
        ArrayOfIvaDTO lstIva);

}
