
package br.gov.sp.saobernardo.paradigma.ws.iva;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Iva", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Iva.svc?wsdl")
public class Iva
    extends Service
{

    private final static URL IVA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.iva.Iva.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.iva.Iva.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Iva.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Iva.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IVA_WSDL_LOCATION = url;
    }

    public Iva(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Iva() {
        super(IVA_WSDL_LOCATION, new QName("http://tempuri.org/", "Iva"));
    }

    /**
     * 
     * @return
     *     returns IIva
     */
    @WebEndpoint(name = "BasicHttpBinding_IIva")
    public IIva getBasicHttpBindingIIva() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IIva"), IIva.class);
    }

}
