
package br.gov.sp.saobernardo.paradigma.ws.convite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IConvite", targetNamespace = "http://tempuri.org/")
public interface IConvite {


    /**
     * 
     * @param lstConvite
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.convite.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarConvite", action = "http://tempuri.org/IConvite/ProcessarConvite")
    @WebResult(name = "ProcessarConviteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarConvite", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.convite.ProcessarConvite")
    @ResponseWrapper(localName = "ProcessarConviteResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.convite.ProcessarConviteResponse")
    public RetornoDTO processarConvite(
        @WebParam(name = "lstConvite", targetNamespace = "http://tempuri.org/")
        ArrayOfConviteDTO lstConvite);

}
