
package br.gov.sp.saobernardo.paradigma.ws.departamento;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Departamento", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Departamento.svc?wsdl")
public class Departamento
    extends Service
{

    private final static URL DEPARTAMENTO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.departamento.Departamento.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.departamento.Departamento.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Departamento.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Departamento.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DEPARTAMENTO_WSDL_LOCATION = url;
    }

    public Departamento(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Departamento() {
        super(DEPARTAMENTO_WSDL_LOCATION, new QName("http://tempuri.org/", "Departamento"));
    }

    /**
     * 
     * @return
     *     returns IDepartamento
     */
    @WebEndpoint(name = "BasicHttpBinding_IDepartamento")
    public IDepartamento getBasicHttpBindingIDepartamento() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDepartamento"), IDepartamento.class);
    }

}
