
package br.gov.sp.saobernardo.paradigma.ws.wfalcada;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IWfAlcada", targetNamespace = "http://tempuri.org/")
public interface IWfAlcada {


    /**
     * 
     * @param lstCdObjeto
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.wfalcada.RetornoListaX003CWfAlcadaDTOX003E
     */
    @WebMethod(operationName = "RetornarAlcada", action = "http://tempuri.org/IWfAlcada/RetornarAlcada")
    @WebResult(name = "RetornarAlcadaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarAlcada", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfalcada.RetornarAlcada")
    @ResponseWrapper(localName = "RetornarAlcadaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfalcada.RetornarAlcadaResponse")
    public RetornoListaX003CWfAlcadaDTOX003E retornarAlcada(
        @WebParam(name = "lstCdObjeto", targetNamespace = "http://tempuri.org/")
        ArrayOflong lstCdObjeto);

    /**
     * 
     * @param wfAlcadaUsuarioPesquisaDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.wfalcada.RetornoListaX003CWfAlcadaUsuarioDTOX003E
     */
    @WebMethod(operationName = "RetornarAlcadaUsuario", action = "http://tempuri.org/IWfAlcada/RetornarAlcadaUsuario")
    @WebResult(name = "RetornarAlcadaUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarAlcadaUsuario", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfalcada.RetornarAlcadaUsuario")
    @ResponseWrapper(localName = "RetornarAlcadaUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfalcada.RetornarAlcadaUsuarioResponse")
    public RetornoListaX003CWfAlcadaUsuarioDTOX003E retornarAlcadaUsuario(
        @WebParam(name = "wfAlcadaUsuarioPesquisaDTO", targetNamespace = "http://tempuri.org/")
        WfAlcadaUsuarioPesquisaDTO wfAlcadaUsuarioPesquisaDTO);

}
