
package br.gov.sp.saobernardo.paradigma.ws.produtocomprahistorico;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ProdutoCompraHistorico", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/ProdutoCompraHistorico.svc?wsdl")
public class ProdutoCompraHistorico
    extends Service
{

    private final static URL PRODUTOCOMPRAHISTORICO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.produtocomprahistorico.ProdutoCompraHistorico.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.produtocomprahistorico.ProdutoCompraHistorico.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/ProdutoCompraHistorico.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/ProdutoCompraHistorico.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PRODUTOCOMPRAHISTORICO_WSDL_LOCATION = url;
    }

    public ProdutoCompraHistorico(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProdutoCompraHistorico() {
        super(PRODUTOCOMPRAHISTORICO_WSDL_LOCATION, new QName("http://tempuri.org/", "ProdutoCompraHistorico"));
    }

    /**
     * 
     * @return
     *     returns IProdutoCompraHistorico
     */
    @WebEndpoint(name = "BasicHttpBinding_IProdutoCompraHistorico")
    public IProdutoCompraHistorico getBasicHttpBindingIProdutoCompraHistorico() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IProdutoCompraHistorico"), IProdutoCompraHistorico.class);
    }

}
