
package br.gov.sp.saobernardo.paradigma.ws.marca;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IMarca", targetNamespace = "http://tempuri.org/")
public interface IMarca {


    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.marca.RetornoListaX003CMarcaDTOX003E
     */
    @WebMethod(operationName = "RetornarMarca", action = "http://tempuri.org/IMarca/RetornarMarca")
    @WebResult(name = "RetornarMarcaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarMarca", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.marca.RetornarMarca")
    @ResponseWrapper(localName = "RetornarMarcaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.marca.RetornarMarcaResponse")
    public RetornoListaX003CMarcaDTOX003E retornarMarca();

    /**
     * 
     * @param sCdProduto
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.marca.RetornoListaX003CMarcaDTOX003E
     */
    @WebMethod(operationName = "RetornarMarcaPorProduto", action = "http://tempuri.org/IMarca/RetornarMarcaPorProduto")
    @WebResult(name = "RetornarMarcaPorProdutoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarMarcaPorProduto", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.marca.RetornarMarcaPorProduto")
    @ResponseWrapper(localName = "RetornarMarcaPorProdutoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.marca.RetornarMarcaPorProdutoResponse")
    public RetornoListaX003CMarcaDTOX003E retornarMarcaPorProduto(
        @WebParam(name = "sCdProduto", targetNamespace = "http://tempuri.org/")
        String sCdProduto);

}
