
package br.gov.sp.saobernardo.paradigma.ws.unidadenegocio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IUnidadeNegocio", targetNamespace = "http://tempuri.org/")
public interface IUnidadeNegocio {


    /**
     * 
     * @param lstUnidadeNegocio
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.unidadenegocio.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarUnidadeNegocio", action = "http://tempuri.org/IUnidadeNegocio/ProcessarUnidadeNegocio")
    @WebResult(name = "ProcessarUnidadeNegocioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarUnidadeNegocio", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.unidadenegocio.ProcessarUnidadeNegocio")
    @ResponseWrapper(localName = "ProcessarUnidadeNegocioResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.unidadenegocio.ProcessarUnidadeNegocioResponse")
    public RetornoDTO processarUnidadeNegocio(
        @WebParam(name = "lstUnidadeNegocio", targetNamespace = "http://tempuri.org/")
        ArrayOfUnidadeNegocioDTO lstUnidadeNegocio);

}
