
package br.gov.sp.saobernardo.paradigma.ws.centrocusto;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CentroCusto", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/CentroCusto.svc?wsdl")
public class CentroCusto
    extends Service
{

    private final static URL CENTROCUSTO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.centrocusto.CentroCusto.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.centrocusto.CentroCusto.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/CentroCusto.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/CentroCusto.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CENTROCUSTO_WSDL_LOCATION = url;
    }

    public CentroCusto(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CentroCusto() {
        super(CENTROCUSTO_WSDL_LOCATION, new QName("http://tempuri.org/", "CentroCusto"));
    }

    /**
     * 
     * @return
     *     returns ICentroCusto
     */
    @WebEndpoint(name = "BasicHttpBinding_ICentroCusto")
    public ICentroCusto getBasicHttpBindingICentroCusto() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICentroCusto"), ICentroCusto.class);
    }

}
