
package br.gov.sp.saobernardo.paradigma.ws.centrocusto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ICentroCusto", targetNamespace = "http://tempuri.org/")
public interface ICentroCusto {


    /**
     * 
     * @param lstCentroCusto
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.centrocusto.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarCentroCusto", action = "http://tempuri.org/ICentroCusto/ProcessarCentroCusto")
    @WebResult(name = "ProcessarCentroCustoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarCentroCusto", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.centrocusto.ProcessarCentroCusto")
    @ResponseWrapper(localName = "ProcessarCentroCustoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.centrocusto.ProcessarCentroCustoResponse")
    public RetornoDTO processarCentroCusto(
        @WebParam(name = "lstCentroCusto", targetNamespace = "http://tempuri.org/")
        ArrayOfCentroCustoDTO lstCentroCusto);

    /**
     * 
     * @param sCdDepartamento
     * @param sFlAtivo
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.centrocusto.RetornoListaX003CCentroCustoDTOX003E
     */
    @WebMethod(operationName = "RetornarCentroCustoPorDepartamento", action = "http://tempuri.org/ICentroCusto/RetornarCentroCustoPorDepartamento")
    @WebResult(name = "RetornarCentroCustoPorDepartamentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarCentroCustoPorDepartamento", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.centrocusto.RetornarCentroCustoPorDepartamento")
    @ResponseWrapper(localName = "RetornarCentroCustoPorDepartamentoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.centrocusto.RetornarCentroCustoPorDepartamentoResponse")
    public RetornoListaX003CCentroCustoDTOX003E retornarCentroCustoPorDepartamento(
        @WebParam(name = "sCdDepartamento", targetNamespace = "http://tempuri.org/")
        String sCdDepartamento,
        @WebParam(name = "sFlAtivo", targetNamespace = "http://tempuri.org/")
        String sFlAtivo);

    /**
     * 
     * @param lstCentroCustoInativarDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.centrocusto.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarInativarCentroCustoDePara", action = "http://tempuri.org/ICentroCusto/ProcessarInativarCentroCustoDePara")
    @WebResult(name = "ProcessarInativarCentroCustoDeParaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarInativarCentroCustoDePara", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.centrocusto.ProcessarInativarCentroCustoDePara")
    @ResponseWrapper(localName = "ProcessarInativarCentroCustoDeParaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.centrocusto.ProcessarInativarCentroCustoDeParaResponse")
    public RetornoDTO processarInativarCentroCustoDePara(
        @WebParam(name = "lstCentroCustoInativarDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfCentroCustoDTO lstCentroCustoInativarDTO);

}
