
package br.gov.sp.saobernardo.paradigma.ws.notafiscaltituloresumida;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "INotaFiscalTituloResumida", targetNamespace = "http://tempuri.org/")
public interface INotaFiscalTituloResumida {


    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.notafiscaltituloresumida.ArrayOfNotaFiscalTituloResumidaDTO
     */
    @WebMethod(operationName = "RetornarNotaFiscal", action = "http://tempuri.org/INotaFiscalTituloResumida/RetornarNotaFiscal")
    @WebResult(name = "RetornarNotaFiscalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarNotaFiscal", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscaltituloresumida.RetornarNotaFiscal")
    @ResponseWrapper(localName = "RetornarNotaFiscalResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscaltituloresumida.RetornarNotaFiscalResponse")
    public ArrayOfNotaFiscalTituloResumidaDTO retornarNotaFiscal();

}
