
package br.gov.sp.saobernardo.paradigma.ws.notafiscaltituloresumida;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "NotaFiscalTituloResumida", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/NotaFiscalTituloResumida.svc?wsdl")
public class NotaFiscalTituloResumida
    extends Service
{

    private final static URL NOTAFISCALTITULORESUMIDA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.notafiscaltituloresumida.NotaFiscalTituloResumida.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.notafiscaltituloresumida.NotaFiscalTituloResumida.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/NotaFiscalTituloResumida.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/NotaFiscalTituloResumida.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NOTAFISCALTITULORESUMIDA_WSDL_LOCATION = url;
    }

    public NotaFiscalTituloResumida(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotaFiscalTituloResumida() {
        super(NOTAFISCALTITULORESUMIDA_WSDL_LOCATION, new QName("http://tempuri.org/", "NotaFiscalTituloResumida"));
    }

    /**
     * 
     * @return
     *     returns INotaFiscalTituloResumida
     */
    @WebEndpoint(name = "BasicHttpBinding_INotaFiscalTituloResumida")
    public INotaFiscalTituloResumida getBasicHttpBindingINotaFiscalTituloResumida() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_INotaFiscalTituloResumida"), INotaFiscalTituloResumida.class);
    }

}
