
package br.gov.sp.saobernardo.paradigma.ws.grupocompra;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "GrupoCompra", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/GrupoCompra.svc?wsdl")
public class GrupoCompra
    extends Service
{

    private final static URL GRUPOCOMPRA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.grupocompra.GrupoCompra.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.grupocompra.GrupoCompra.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/GrupoCompra.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/GrupoCompra.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GRUPOCOMPRA_WSDL_LOCATION = url;
    }

    public GrupoCompra(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GrupoCompra() {
        super(GRUPOCOMPRA_WSDL_LOCATION, new QName("http://tempuri.org/", "GrupoCompra"));
    }

    /**
     * 
     * @return
     *     returns IGrupoCompra
     */
    @WebEndpoint(name = "BasicHttpBinding_IGrupoCompra")
    public IGrupoCompra getBasicHttpBindingIGrupoCompra() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IGrupoCompra"), IGrupoCompra.class);
    }

}
