
package br.gov.sp.saobernardo.paradigma.ws.grupocompra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IGrupoCompra", targetNamespace = "http://tempuri.org/")
public interface IGrupoCompra {


    /**
     * 
     * @param lstGrupoCompra
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.grupocompra.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarGrupoCompra", action = "http://tempuri.org/IGrupoCompra/ProcessarGrupoCompra")
    @WebResult(name = "ProcessarGrupoCompraResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarGrupoCompra", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.grupocompra.ProcessarGrupoCompra")
    @ResponseWrapper(localName = "ProcessarGrupoCompraResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.grupocompra.ProcessarGrupoCompraResponse")
    public RetornoDTO processarGrupoCompra(
        @WebParam(name = "lstGrupoCompra", targetNamespace = "http://tempuri.org/")
        ArrayOfGrupoCompraDTO lstGrupoCompra);

}
