
package br.gov.sp.saobernardo.paradigma.ws.naturezadespesa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "INaturezaDespesa", targetNamespace = "http://tempuri.org/")
public interface INaturezaDespesa {


    /**
     * 
     * @param lstNaturezaDespesa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.naturezadespesa.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarNaturezaDespesa", action = "http://tempuri.org/INaturezaDespesa/ProcessarNaturezaDespesa")
    @WebResult(name = "ProcessarNaturezaDespesaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarNaturezaDespesa", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.naturezadespesa.ProcessarNaturezaDespesa")
    @ResponseWrapper(localName = "ProcessarNaturezaDespesaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.naturezadespesa.ProcessarNaturezaDespesaResponse")
    public RetornoDTO processarNaturezaDespesa(
        @WebParam(name = "lstNaturezaDespesa", targetNamespace = "http://tempuri.org/")
        ArrayOfNaturezaDespesaDTO lstNaturezaDespesa);

    /**
     * 
     * @param sCdProduto
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.naturezadespesa.RetornoListaX003CNaturezaDespesaDTOX003E
     */
    @WebMethod(operationName = "RetornarNaturezaDespesaPorProduto", action = "http://tempuri.org/INaturezaDespesa/RetornarNaturezaDespesaPorProduto")
    @WebResult(name = "RetornarNaturezaDespesaPorProdutoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarNaturezaDespesaPorProduto", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.naturezadespesa.RetornarNaturezaDespesaPorProduto")
    @ResponseWrapper(localName = "RetornarNaturezaDespesaPorProdutoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.naturezadespesa.RetornarNaturezaDespesaPorProdutoResponse")
    public RetornoListaX003CNaturezaDespesaDTOX003E retornarNaturezaDespesaPorProduto(
        @WebParam(name = "sCdProduto", targetNamespace = "http://tempuri.org/")
        String sCdProduto);

}
