
package br.gov.sp.saobernardo.paradigma.ws.naturezadespesa;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "NaturezaDespesa", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/NaturezaDespesa.svc?wsdl")
public class NaturezaDespesa
    extends Service
{

    private final static URL NATUREZADESPESA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.naturezadespesa.NaturezaDespesa.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.naturezadespesa.NaturezaDespesa.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/NaturezaDespesa.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/NaturezaDespesa.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NATUREZADESPESA_WSDL_LOCATION = url;
    }

    public NaturezaDespesa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NaturezaDespesa() {
        super(NATUREZADESPESA_WSDL_LOCATION, new QName("http://tempuri.org/", "NaturezaDespesa"));
    }

    /**
     * 
     * @return
     *     returns INaturezaDespesa
     */
    @WebEndpoint(name = "BasicHttpBinding_INaturezaDespesa")
    public INaturezaDespesa getBasicHttpBindingINaturezaDespesa() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_INaturezaDespesa"), INaturezaDespesa.class);
    }

}
