
package br.gov.sp.saobernardo.paradigma.ws.banco;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Banco", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Banco.svc?wsdl")
public class Banco
    extends Service
{

    private final static URL BANCO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.banco.Banco.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.banco.Banco.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Banco.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Banco.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BANCO_WSDL_LOCATION = url;
    }

    public Banco(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Banco() {
        super(BANCO_WSDL_LOCATION, new QName("http://tempuri.org/", "Banco"));
    }

    /**
     * 
     * @return
     *     returns IBanco
     */
    @WebEndpoint(name = "BasicHttpBinding_IBanco")
    public IBanco getBasicHttpBindingIBanco() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBanco"), IBanco.class);
    }

}
