
package br.gov.sp.saobernardo.paradigma.ws.banco;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IBanco", targetNamespace = "http://tempuri.org/")
public interface IBanco {


    /**
     * 
     * @param lstBanco
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.banco.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarBanco", action = "http://tempuri.org/IBanco/ProcessarBanco")
    @WebResult(name = "ProcessarBancoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarBanco", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.banco.ProcessarBanco")
    @ResponseWrapper(localName = "ProcessarBancoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.banco.ProcessarBancoResponse")
    public RetornoDTO processarBanco(
        @WebParam(name = "lstBanco", targetNamespace = "http://tempuri.org/")
        ArrayOfBancoDTO lstBanco);

    /**
     * 
     * @param lstAgenciaBanco
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.banco.RetornoDTO
     */
    @WebMethod(operationName = "ExcluirAgenciaBanco", action = "http://tempuri.org/IBanco/ExcluirAgenciaBanco")
    @WebResult(name = "ExcluirAgenciaBancoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExcluirAgenciaBanco", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.banco.ExcluirAgenciaBanco")
    @ResponseWrapper(localName = "ExcluirAgenciaBancoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.banco.ExcluirAgenciaBancoResponse")
    public RetornoDTO excluirAgenciaBanco(
        @WebParam(name = "lstAgenciaBanco", targetNamespace = "http://tempuri.org/")
        ArrayOfAgenciaBancoExclusaoDTO lstAgenciaBanco);

}
