
package br.gov.sp.saobernardo.paradigma.ws.empresaclasse;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "EmpresaClasse", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/EmpresaClasse.svc?wsdl")
public class EmpresaClasse
    extends Service
{

    private final static URL EMPRESACLASSE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.empresaclasse.EmpresaClasse.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.empresaclasse.EmpresaClasse.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/EmpresaClasse.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/EmpresaClasse.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EMPRESACLASSE_WSDL_LOCATION = url;
    }

    public EmpresaClasse(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpresaClasse() {
        super(EMPRESACLASSE_WSDL_LOCATION, new QName("http://tempuri.org/", "EmpresaClasse"));
    }

    /**
     * 
     * @return
     *     returns IEmpresaClasse
     */
    @WebEndpoint(name = "BasicHttpBinding_IEmpresaClasse")
    public IEmpresaClasse getBasicHttpBindingIEmpresaClasse() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEmpresaClasse"), IEmpresaClasse.class);
    }

}
