
package br.gov.sp.saobernardo.paradigma.ws.notafiscal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "INotaFiscal", targetNamespace = "http://tempuri.org/")
public interface INotaFiscal {


    /**
     * 
     * @param lstNotaFiscal
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.notafiscal.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarNotaFiscal", action = "http://tempuri.org/INotaFiscal/ProcessarNotaFiscal")
    @WebResult(name = "ProcessarNotaFiscalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarNotaFiscal", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscal.ProcessarNotaFiscal")
    @ResponseWrapper(localName = "ProcessarNotaFiscalResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscal.ProcessarNotaFiscalResponse")
    public RetornoDTO processarNotaFiscal(
        @WebParam(name = "lstNotaFiscal", targetNamespace = "http://tempuri.org/")
        ArrayOfNotaFiscalDTO lstNotaFiscal);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.notafiscal.ArrayOfNotaFiscalDTO
     */
    @WebMethod(operationName = "RetornarNotaFiscal", action = "http://tempuri.org/INotaFiscal/RetornarNotaFiscal")
    @WebResult(name = "RetornarNotaFiscalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarNotaFiscal", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscal.RetornarNotaFiscal")
    @ResponseWrapper(localName = "RetornarNotaFiscalResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscal.RetornarNotaFiscalResponse")
    public ArrayOfNotaFiscalDTO retornarNotaFiscal();

    /**
     * 
     * @param lstLog
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.notafiscal.RetornoDTO
     */
    @WebMethod(operationName = "RetornarNotaFiscalFalha", action = "http://tempuri.org/INotaFiscal/RetornarNotaFiscalFalha")
    @WebResult(name = "RetornarNotaFiscalFalhaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarNotaFiscalFalha", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscal.RetornarNotaFiscalFalha")
    @ResponseWrapper(localName = "RetornarNotaFiscalFalhaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscal.RetornarNotaFiscalFalhaResponse")
    public RetornoDTO retornarNotaFiscalFalha(
        @WebParam(name = "lstLog", targetNamespace = "http://tempuri.org/")
        ArrayOfWbtLogCapaDTO lstLog);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.notafiscal.RetornoListaX003CNotaFiscalDTOX003E
     */
    @WebMethod(operationName = "RetornarNotaFiscalRecebida", action = "http://tempuri.org/INotaFiscal/RetornarNotaFiscalRecebida")
    @WebResult(name = "RetornarNotaFiscalRecebidaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarNotaFiscalRecebida", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscal.RetornarNotaFiscalRecebida")
    @ResponseWrapper(localName = "RetornarNotaFiscalRecebidaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscal.RetornarNotaFiscalRecebidaResponse")
    public RetornoListaX003CNotaFiscalDTOX003E retornarNotaFiscalRecebida();

    /**
     * 
     * @param lstNotaFiscalFiltroDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.notafiscal.RetornoDTO
     */
    @WebMethod(operationName = "ConfirmarProcessamentoRetornoNotaFiscal", action = "http://tempuri.org/INotaFiscal/ConfirmarProcessamentoRetornoNotaFiscal")
    @WebResult(name = "ConfirmarProcessamentoRetornoNotaFiscalResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmarProcessamentoRetornoNotaFiscal", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscal.ConfirmarProcessamentoRetornoNotaFiscal")
    @ResponseWrapper(localName = "ConfirmarProcessamentoRetornoNotaFiscalResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.notafiscal.ConfirmarProcessamentoRetornoNotaFiscalResponse")
    public RetornoDTO confirmarProcessamentoRetornoNotaFiscal(
        @WebParam(name = "lstNotaFiscalFiltroDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfNotaFiscalFiltroDTO lstNotaFiscalFiltroDTO);

}
