
package br.gov.sp.saobernardo.paradigma.ws.grupoconta;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "GrupoConta", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/GrupoConta.svc?wsdl")
public class GrupoConta
    extends Service
{

    private final static URL GRUPOCONTA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.grupoconta.GrupoConta.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.grupoconta.GrupoConta.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/GrupoConta.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/GrupoConta.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GRUPOCONTA_WSDL_LOCATION = url;
    }

    public GrupoConta(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GrupoConta() {
        super(GRUPOCONTA_WSDL_LOCATION, new QName("http://tempuri.org/", "GrupoConta"));
    }

    /**
     * 
     * @return
     *     returns IGrupoConta
     */
    @WebEndpoint(name = "BasicHttpBinding_IGrupoConta")
    public IGrupoConta getBasicHttpBindingIGrupoConta() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IGrupoConta"), IGrupoConta.class);
    }

}
