
package br.gov.sp.saobernardo.paradigma.ws.grupoconta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IGrupoConta", targetNamespace = "http://tempuri.org/")
public interface IGrupoConta {


    /**
     * 
     * @param lstGrupoConta
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.grupoconta.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarGrupoConta", action = "http://tempuri.org/IGrupoConta/ProcessarGrupoConta")
    @WebResult(name = "ProcessarGrupoContaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarGrupoConta", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.grupoconta.ProcessarGrupoConta")
    @ResponseWrapper(localName = "ProcessarGrupoContaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.grupoconta.ProcessarGrupoContaResponse")
    public RetornoDTO processarGrupoConta(
        @WebParam(name = "lstGrupoConta", targetNamespace = "http://tempuri.org/")
        ArrayOfGrupoContaDTO lstGrupoConta);

    /**
     * 
     * @param lstGrupoContaEmpresa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.grupoconta.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarGrupoContaEmpresa", action = "http://tempuri.org/IGrupoConta/ProcessarGrupoContaEmpresa")
    @WebResult(name = "ProcessarGrupoContaEmpresaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarGrupoContaEmpresa", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.grupoconta.ProcessarGrupoContaEmpresa")
    @ResponseWrapper(localName = "ProcessarGrupoContaEmpresaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.grupoconta.ProcessarGrupoContaEmpresaResponse")
    public RetornoDTO processarGrupoContaEmpresa(
        @WebParam(name = "lstGrupoContaEmpresa", targetNamespace = "http://tempuri.org/")
        ArrayOfGrupoContaEmpresaDTO lstGrupoContaEmpresa);

}
