
package br.gov.sp.saobernardo.paradigma.ws.patrimonio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IPatrimonio", targetNamespace = "http://tempuri.org/")
public interface IPatrimonio {


    /**
     * 
     * @param lstIventarioMovelDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarInventarioMovel", action = "http://tempuri.org/IPatrimonio/ProcessarInventarioMovel")
    @WebResult(name = "ProcessarInventarioMovelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarInventarioMovel", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.ProcessarInventarioMovel")
    @ResponseWrapper(localName = "ProcessarInventarioMovelResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.ProcessarInventarioMovelResponse")
    public RetornoDTO processarInventarioMovel(
        @WebParam(name = "lstIventarioMovelDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfInventarioMovelDTO lstIventarioMovelDTO);

    /**
     * 
     * @param sCdInventarioSelecionado
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornoListaX003CInventarioMovelDTOX003E
     */
    @WebMethod(operationName = "RetornarInventarioMovel", action = "http://tempuri.org/IPatrimonio/RetornarInventarioMovel")
    @WebResult(name = "RetornarInventarioMovelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarInventarioMovel", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornarInventarioMovel")
    @ResponseWrapper(localName = "RetornarInventarioMovelResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornarInventarioMovelResponse")
    public RetornoListaX003CInventarioMovelDTOX003E retornarInventarioMovel(
        @WebParam(name = "sCdInventarioSelecionado", targetNamespace = "http://tempuri.org/")
        String sCdInventarioSelecionado);

    /**
     * 
     * @param sCdUsuaioErp
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarMudancaResponsavel", action = "http://tempuri.org/IPatrimonio/ProcessarMudancaResponsavel")
    @WebResult(name = "ProcessarMudancaResponsavelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarMudancaResponsavel", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.ProcessarMudancaResponsavel")
    @ResponseWrapper(localName = "ProcessarMudancaResponsavelResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.ProcessarMudancaResponsavelResponse")
    public RetornoDTO processarMudancaResponsavel(
        @WebParam(name = "sCdUsuaioErp", targetNamespace = "http://tempuri.org/")
        String sCdUsuaioErp);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornoListaX003CDadosContabeisDTOX003E
     */
    @WebMethod(operationName = "RetornaDadosContabeisMovel", action = "http://tempuri.org/IPatrimonio/RetornaDadosContabeisMovel")
    @WebResult(name = "RetornaDadosContabeisMovelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornaDadosContabeisMovel", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornaDadosContabeisMovel")
    @ResponseWrapper(localName = "RetornaDadosContabeisMovelResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornaDadosContabeisMovelResponse")
    public RetornoListaX003CDadosContabeisDTOX003E retornaDadosContabeisMovel();

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornoListaX003CDadosContabeisDTOX003E
     */
    @WebMethod(operationName = "RetornaDadosContabeisImovel", action = "http://tempuri.org/IPatrimonio/RetornaDadosContabeisImovel")
    @WebResult(name = "RetornaDadosContabeisImovelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornaDadosContabeisImovel", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornaDadosContabeisImovel")
    @ResponseWrapper(localName = "RetornaDadosContabeisImovelResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornaDadosContabeisImovelResponse")
    public RetornoListaX003CDadosContabeisDTOX003E retornaDadosContabeisImovel();

    /**
     * 
     * @param lstNumeroDocumentoContabilDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarNumeroDocumentoContabil", action = "http://tempuri.org/IPatrimonio/ProcessarNumeroDocumentoContabil")
    @WebResult(name = "ProcessarNumeroDocumentoContabilResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarNumeroDocumentoContabil", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.ProcessarNumeroDocumentoContabil")
    @ResponseWrapper(localName = "ProcessarNumeroDocumentoContabilResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.ProcessarNumeroDocumentoContabilResponse")
    public RetornoDTO processarNumeroDocumentoContabil(
        @WebParam(name = "lstNumeroDocumentoContabilDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfNumeroDocumentoContabilDTO lstNumeroDocumentoContabilDTO);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornoListaX003CDadosContabeisEstornoDTOX003E
     */
    @WebMethod(operationName = "RetornaDadosContabeisEstorno", action = "http://tempuri.org/IPatrimonio/RetornaDadosContabeisEstorno")
    @WebResult(name = "RetornaDadosContabeisEstornoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornaDadosContabeisEstorno", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornaDadosContabeisEstorno")
    @ResponseWrapper(localName = "RetornaDadosContabeisEstornoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.patrimonio.RetornaDadosContabeisEstornoResponse")
    public RetornoListaX003CDadosContabeisEstornoDTOX003E retornaDadosContabeisEstorno();

}
