
package br.gov.sp.saobernardo.paradigma.ws.produtounidademedida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IProdutoUnidadeMedida", targetNamespace = "http://tempuri.org/")
public interface IProdutoUnidadeMedida {


    /**
     * 
     * @param lstProdutoUnidadeMedida
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produtounidademedida.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarProdutoUnidadeMedida", action = "http://tempuri.org/IProdutoUnidadeMedida/ProcessarProdutoUnidadeMedida")
    @WebResult(name = "ProcessarProdutoUnidadeMedidaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarProdutoUnidadeMedida", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produtounidademedida.ProcessarProdutoUnidadeMedida")
    @ResponseWrapper(localName = "ProcessarProdutoUnidadeMedidaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produtounidademedida.ProcessarProdutoUnidadeMedidaResponse")
    public RetornoDTO processarProdutoUnidadeMedida(
        @WebParam(name = "lstProdutoUnidadeMedida", targetNamespace = "http://tempuri.org/")
        ArrayOfProdutoUnidadeMedidaDTO lstProdutoUnidadeMedida);

}
