
package br.gov.sp.saobernardo.paradigma.ws.produtonaturezadespesa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IProdutoNaturezaDespesa", targetNamespace = "http://tempuri.org/")
public interface IProdutoNaturezaDespesa {


    /**
     * 
     * @param lstProdutoNaturezaDespesa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produtonaturezadespesa.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarProdutoNaturezaDespesa", action = "http://tempuri.org/IProdutoNaturezaDespesa/ProcessarProdutoNaturezaDespesa")
    @WebResult(name = "ProcessarProdutoNaturezaDespesaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarProdutoNaturezaDespesa", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produtonaturezadespesa.ProcessarProdutoNaturezaDespesa")
    @ResponseWrapper(localName = "ProcessarProdutoNaturezaDespesaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produtonaturezadespesa.ProcessarProdutoNaturezaDespesaResponse")
    public RetornoDTO processarProdutoNaturezaDespesa(
        @WebParam(name = "lstProdutoNaturezaDespesa", targetNamespace = "http://tempuri.org/")
        ArrayOfProdutoNaturezaDespesaDTO lstProdutoNaturezaDespesa);

    /**
     * 
     * @param lstProdutoNaturezaDespesa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produtonaturezadespesa.RetornoDTO
     */
    @WebMethod(operationName = "ExcluirProdutoNaturezaDespesa", action = "http://tempuri.org/IProdutoNaturezaDespesa/ExcluirProdutoNaturezaDespesa")
    @WebResult(name = "ExcluirProdutoNaturezaDespesaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExcluirProdutoNaturezaDespesa", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produtonaturezadespesa.ExcluirProdutoNaturezaDespesa")
    @ResponseWrapper(localName = "ExcluirProdutoNaturezaDespesaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produtonaturezadespesa.ExcluirProdutoNaturezaDespesaResponse")
    public RetornoDTO excluirProdutoNaturezaDespesa(
        @WebParam(name = "lstProdutoNaturezaDespesa", targetNamespace = "http://tempuri.org/")
        ArrayOfProdutoNaturezaDespesaDTO lstProdutoNaturezaDespesa);

}
