
package br.gov.sp.saobernardo.paradigma.ws.produtonaturezadespesa;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ProdutoNaturezaDespesa", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/ProdutoNaturezaDespesa.svc?wsdl")
public class ProdutoNaturezaDespesa
    extends Service
{

    private final static URL PRODUTONATUREZADESPESA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.produtonaturezadespesa.ProdutoNaturezaDespesa.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.produtonaturezadespesa.ProdutoNaturezaDespesa.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/ProdutoNaturezaDespesa.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/ProdutoNaturezaDespesa.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PRODUTONATUREZADESPESA_WSDL_LOCATION = url;
    }

    public ProdutoNaturezaDespesa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProdutoNaturezaDespesa() {
        super(PRODUTONATUREZADESPESA_WSDL_LOCATION, new QName("http://tempuri.org/", "ProdutoNaturezaDespesa"));
    }

    /**
     * 
     * @return
     *     returns IProdutoNaturezaDespesa
     */
    @WebEndpoint(name = "BasicHttpBinding_IProdutoNaturezaDespesa")
    public IProdutoNaturezaDespesa getBasicHttpBindingIProdutoNaturezaDespesa() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IProdutoNaturezaDespesa"), IProdutoNaturezaDespesa.class);
    }

}
