
package br.gov.sp.saobernardo.paradigma.ws.wbtlog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IWbtLog", targetNamespace = "http://tempuri.org/")
public interface IWbtLog {


    /**
     * 
     * @param sCdOrigem
     * @param sNrToken
     * @param sDsLog
     * @param sDsLogDetalhado
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.wbtlog.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarErroLog", action = "http://tempuri.org/IWbtLog/ProcessarErroLog")
    @WebResult(name = "ProcessarErroLogResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarErroLog", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtlog.ProcessarErroLog")
    @ResponseWrapper(localName = "ProcessarErroLogResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtlog.ProcessarErroLogResponse")
    public RetornoDTO processarErroLog(
        @WebParam(name = "sDsLog", targetNamespace = "http://tempuri.org/")
        String sDsLog,
        @WebParam(name = "sDsLogDetalhado", targetNamespace = "http://tempuri.org/")
        String sDsLogDetalhado,
        @WebParam(name = "sNrToken", targetNamespace = "http://tempuri.org/")
        String sNrToken,
        @WebParam(name = "sCdOrigem", targetNamespace = "http://tempuri.org/")
        String sCdOrigem);

    /**
     * 
     * @param lstIdentificadores
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.wbtlog.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarErrosIntegracaoLog", action = "http://tempuri.org/IWbtLog/ProcessarErrosIntegracaoLog")
    @WebResult(name = "ProcessarErrosIntegracaoLogResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarErrosIntegracaoLog", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtlog.ProcessarErrosIntegracaoLog")
    @ResponseWrapper(localName = "ProcessarErrosIntegracaoLogResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtlog.ProcessarErrosIntegracaoLogResponse")
    public RetornoDTO processarErrosIntegracaoLog(
        @WebParam(name = "lstIdentificadores", targetNamespace = "http://tempuri.org/")
        ArrayOfint lstIdentificadores);

}
