
package br.gov.sp.saobernardo.paradigma.ws.wbtlog;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WbtLog", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/WbtLog.svc?wsdl")
public class WbtLog
    extends Service
{

    private final static URL WBTLOG_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.wbtlog.WbtLog.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.wbtlog.WbtLog.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/WbtLog.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/WbtLog.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WBTLOG_WSDL_LOCATION = url;
    }

    public WbtLog(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WbtLog() {
        super(WBTLOG_WSDL_LOCATION, new QName("http://tempuri.org/", "WbtLog"));
    }

    /**
     * 
     * @return
     *     returns IWbtLog
     */
    @WebEndpoint(name = "BasicHttpBinding_IWbtLog")
    public IWbtLog getBasicHttpBindingIWbtLog() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWbtLog"), IWbtLog.class);
    }

}
