
package br.gov.sp.saobernardo.paradigma.ws.almoxarifado;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Almoxarifado", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Almoxarifado.svc?wsdl")
public class Almoxarifado
    extends Service
{

    private final static URL ALMOXARIFADO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.almoxarifado.Almoxarifado.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.almoxarifado.Almoxarifado.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Almoxarifado.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Almoxarifado.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ALMOXARIFADO_WSDL_LOCATION = url;
    }

    public Almoxarifado(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Almoxarifado() {
        super(ALMOXARIFADO_WSDL_LOCATION, new QName("http://tempuri.org/", "Almoxarifado"));
    }

    /**
     * 
     * @return
     *     returns IAlmoxarifado
     */
    @WebEndpoint(name = "BasicHttpBinding_IAlmoxarifado")
    public IAlmoxarifado getBasicHttpBindingIAlmoxarifado() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAlmoxarifado"), IAlmoxarifado.class);
    }

}
