
package br.gov.sp.saobernardo.paradigma.ws.almoxarifado;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IAlmoxarifado", targetNamespace = "http://tempuri.org/")
public interface IAlmoxarifado {


    /**
     * 
     * @param lstAlmoxarifado
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarAlmoxarifado", action = "http://tempuri.org/IAlmoxarifado/ProcessarAlmoxarifado")
    @WebResult(name = "ProcessarAlmoxarifadoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarAlmoxarifado", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessarAlmoxarifado")
    @ResponseWrapper(localName = "ProcessarAlmoxarifadoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessarAlmoxarifadoResponse")
    public RetornoDTO processarAlmoxarifado(
        @WebParam(name = "lstAlmoxarifado", targetNamespace = "http://tempuri.org/")
        ArrayOfAlmoxarifadoDTO lstAlmoxarifado);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoListaX003CDocumentoHabilDTOX003E
     */
    @WebMethod(operationName = "RetornarDocumentoHabil", action = "http://tempuri.org/IAlmoxarifado/RetornarDocumentoHabil")
    @WebResult(name = "RetornarDocumentoHabilResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarDocumentoHabil", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarDocumentoHabil")
    @ResponseWrapper(localName = "RetornarDocumentoHabilResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarDocumentoHabilResponse")
    public RetornoListaX003CDocumentoHabilDTOX003E retornarDocumentoHabil();

    /**
     * 
     * @param lstSequencialDocumentoHabilDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarSequencialDocumentoOrigem", action = "http://tempuri.org/IAlmoxarifado/ProcessarSequencialDocumentoOrigem")
    @WebResult(name = "ProcessarSequencialDocumentoOrigemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarSequencialDocumentoOrigem", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessarSequencialDocumentoOrigem")
    @ResponseWrapper(localName = "ProcessarSequencialDocumentoOrigemResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessarSequencialDocumentoOrigemResponse")
    public RetornoDTO processarSequencialDocumentoOrigem(
        @WebParam(name = "lstSequencialDocumentoHabilDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfSequencialDocumentoHabilDTO lstSequencialDocumentoHabilDTO);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoListaX003CDadosContabeisAlmoxarifadoDTOX003E
     */
    @WebMethod(operationName = "RetornarAcaoContabil", action = "http://tempuri.org/IAlmoxarifado/RetornarAcaoContabil")
    @WebResult(name = "RetornarAcaoContabilResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarAcaoContabil", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarAcaoContabil")
    @ResponseWrapper(localName = "RetornarAcaoContabilResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarAcaoContabilResponse")
    public RetornoListaX003CDadosContabeisAlmoxarifadoDTOX003E retornarAcaoContabil();

    /**
     * 
     * @param lstNumeroDocumentoContabilDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarNumeroDocumentoContabilAlmoxarifado", action = "http://tempuri.org/IAlmoxarifado/ProcessarNumeroDocumentoContabilAlmoxarifado")
    @WebResult(name = "ProcessarNumeroDocumentoContabilAlmoxarifadoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarNumeroDocumentoContabilAlmoxarifado", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessarNumeroDocumentoContabilAlmoxarifado")
    @ResponseWrapper(localName = "ProcessarNumeroDocumentoContabilAlmoxarifadoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessarNumeroDocumentoContabilAlmoxarifadoResponse")
    public RetornoDTO processarNumeroDocumentoContabilAlmoxarifado(
        @WebParam(name = "lstNumeroDocumentoContabilDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfNumeroDocumentoContabilAlmoxarifadoDTO lstNumeroDocumentoContabilDTO);

    /**
     * 
     * @param lstNumeroDocumentoHabilDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoDTO
     */
    @WebMethod(operationName = "ProcessaNumeroDocumentoHabil", action = "http://tempuri.org/IAlmoxarifado/ProcessaNumeroDocumentoHabil")
    @WebResult(name = "ProcessaNumeroDocumentoHabilResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessaNumeroDocumentoHabil", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessaNumeroDocumentoHabil")
    @ResponseWrapper(localName = "ProcessaNumeroDocumentoHabilResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessaNumeroDocumentoHabilResponse")
    public RetornoDTO processaNumeroDocumentoHabil(
        @WebParam(name = "lstNumeroDocumentoHabilDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfNumeroDocumentoHabilDTO lstNumeroDocumentoHabilDTO);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoListaX003CAtestoDocumentoHabilDTOX003E
     */
    @WebMethod(operationName = "RetornarAtestoDocumentoHabil", action = "http://tempuri.org/IAlmoxarifado/RetornarAtestoDocumentoHabil")
    @WebResult(name = "RetornarAtestoDocumentoHabilResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarAtestoDocumentoHabil", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarAtestoDocumentoHabil")
    @ResponseWrapper(localName = "RetornarAtestoDocumentoHabilResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarAtestoDocumentoHabilResponse")
    public RetornoListaX003CAtestoDocumentoHabilDTOX003E retornarAtestoDocumentoHabil();

    /**
     * 
     * @param lstAtestoDocumentoHabilDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarAtestoDocumentoHabil", action = "http://tempuri.org/IAlmoxarifado/ProcessarAtestoDocumentoHabil")
    @WebResult(name = "ProcessarAtestoDocumentoHabilResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarAtestoDocumentoHabil", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessarAtestoDocumentoHabil")
    @ResponseWrapper(localName = "ProcessarAtestoDocumentoHabilResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessarAtestoDocumentoHabilResponse")
    public RetornoDTO processarAtestoDocumentoHabil(
        @WebParam(name = "lstAtestoDocumentoHabilDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfRetornoAtestoDocumentoHabilDTO lstAtestoDocumentoHabilDTO);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoListaX003CExcluirDocumentoOrigemDTOX003E
     */
    @WebMethod(operationName = "RetornarExcluirDocumentoOrigem", action = "http://tempuri.org/IAlmoxarifado/RetornarExcluirDocumentoOrigem")
    @WebResult(name = "RetornarExcluirDocumentoOrigemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarExcluirDocumentoOrigem", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarExcluirDocumentoOrigem")
    @ResponseWrapper(localName = "RetornarExcluirDocumentoOrigemResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarExcluirDocumentoOrigemResponse")
    public RetornoListaX003CExcluirDocumentoOrigemDTOX003E retornarExcluirDocumentoOrigem();

    /**
     * 
     * @param lstSequencialDocumentoOrigemDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarExcluirDocumentoOrigem", action = "http://tempuri.org/IAlmoxarifado/ProcessarExcluirDocumentoOrigem")
    @WebResult(name = "ProcessarExcluirDocumentoOrigemResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarExcluirDocumentoOrigem", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessarExcluirDocumentoOrigem")
    @ResponseWrapper(localName = "ProcessarExcluirDocumentoOrigemResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ProcessarExcluirDocumentoOrigemResponse")
    public RetornoDTO processarExcluirDocumentoOrigem(
        @WebParam(name = "lstSequencialDocumentoOrigemDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfSequencialDocumentoOrigemDTO lstSequencialDocumentoOrigemDTO);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoListaX003CAlmoxarifadoDTOX003E
     */
    @WebMethod(operationName = "RetornarAlmoxarifado", action = "http://tempuri.org/IAlmoxarifado/RetornarAlmoxarifado")
    @WebResult(name = "RetornarAlmoxarifadoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarAlmoxarifado", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarAlmoxarifado")
    @ResponseWrapper(localName = "RetornarAlmoxarifadoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarAlmoxarifadoResponse")
    public RetornoListaX003CAlmoxarifadoDTOX003E retornarAlmoxarifado();

    /**
     * 
     * @param oAmxKardexFiltroDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoListaX003CAmxKardexDTOX003E
     */
    @WebMethod(operationName = "RetornarMovimentacao", action = "http://tempuri.org/IAlmoxarifado/RetornarMovimentacao")
    @WebResult(name = "RetornarMovimentacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarMovimentacao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarMovimentacao")
    @ResponseWrapper(localName = "RetornarMovimentacaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornarMovimentacaoResponse")
    public RetornoListaX003CAmxKardexDTOX003E retornarMovimentacao(
        @WebParam(name = "oAmxKardexFiltroDTO", targetNamespace = "http://tempuri.org/")
        AmxKardexFiltroDTO oAmxKardexFiltroDTO);

    /**
     * 
     * @param lstCdKardec
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.almoxarifado.RetornoDTO
     */
    @WebMethod(operationName = "ConfirmarProcessamentoMovimentacao", action = "http://tempuri.org/IAlmoxarifado/ConfirmarProcessamentoMovimentacao")
    @WebResult(name = "ConfirmarProcessamentoMovimentacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmarProcessamentoMovimentacao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ConfirmarProcessamentoMovimentacao")
    @ResponseWrapper(localName = "ConfirmarProcessamentoMovimentacaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.almoxarifado.ConfirmarProcessamentoMovimentacaoResponse")
    public RetornoDTO confirmarProcessamentoMovimentacao(
        @WebParam(name = "lstCdKardec", targetNamespace = "http://tempuri.org/")
        ArrayOflong lstCdKardec);

}
