
package br.gov.sp.saobernardo.paradigma.ws.gestao;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Gestao", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Gestao.svc?wsdl")
public class Gestao
    extends Service
{

    private final static URL GESTAO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.gestao.Gestao.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.gestao.Gestao.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Gestao.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Gestao.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GESTAO_WSDL_LOCATION = url;
    }

    public Gestao(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Gestao() {
        super(GESTAO_WSDL_LOCATION, new QName("http://tempuri.org/", "Gestao"));
    }

    /**
     * 
     * @return
     *     returns IGestao
     */
    @WebEndpoint(name = "BasicHttpBinding_IGestao")
    public IGestao getBasicHttpBindingIGestao() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IGestao"), IGestao.class);
    }

}
