
package br.gov.sp.saobernardo.paradigma.ws.gestao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IGestao", targetNamespace = "http://tempuri.org/")
public interface IGestao {


    /**
     * 
     * @param lstGestao
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.gestao.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarGestao", action = "http://tempuri.org/IGestao/ProcessarGestao")
    @WebResult(name = "ProcessarGestaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarGestao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.gestao.ProcessarGestao")
    @ResponseWrapper(localName = "ProcessarGestaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.gestao.ProcessarGestaoResponse")
    public RetornoDTO processarGestao(
        @WebParam(name = "lstGestao", targetNamespace = "http://tempuri.org/")
        ArrayOfGestaoDTO lstGestao);

}
