
package br.gov.sp.saobernardo.paradigma.ws.compradireta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ICompraDireta", targetNamespace = "http://tempuri.org/")
public interface ICompraDireta {


    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.compradireta.ArrayOfCompraDiretaDTO
     */
    @WebMethod(operationName = "RetornarCompraDireta", action = "http://tempuri.org/ICompraDireta/RetornarCompraDireta")
    @WebResult(name = "RetornarCompraDiretaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarCompraDireta", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.compradireta.RetornarCompraDireta")
    @ResponseWrapper(localName = "RetornarCompraDiretaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.compradireta.RetornarCompraDiretaResponse")
    public ArrayOfCompraDiretaDTO retornarCompraDireta();

    /**
     * 
     * @param lstCompraDireta
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.compradireta.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarCompraDireta", action = "http://tempuri.org/ICompraDireta/ProcessarCompraDireta")
    @WebResult(name = "ProcessarCompraDiretaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarCompraDireta", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.compradireta.ProcessarCompraDireta")
    @ResponseWrapper(localName = "ProcessarCompraDiretaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.compradireta.ProcessarCompraDiretaResponse")
    public RetornoDTO processarCompraDireta(
        @WebParam(name = "lstCompraDireta", targetNamespace = "http://tempuri.org/")
        ArrayOfCompraDiretaDTO lstCompraDireta);

    /**
     * 
     * @param lstCompraDiretaHabilitar
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.compradireta.RetornoDTO
     */
    @WebMethod(operationName = "HabilitarRetornarCompraDireta", action = "http://tempuri.org/ICompraDireta/HabilitarRetornarCompraDireta")
    @WebResult(name = "HabilitarRetornarCompraDiretaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HabilitarRetornarCompraDireta", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.compradireta.HabilitarRetornarCompraDireta")
    @ResponseWrapper(localName = "HabilitarRetornarCompraDiretaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.compradireta.HabilitarRetornarCompraDiretaResponse")
    public RetornoDTO habilitarRetornarCompraDireta(
        @WebParam(name = "lstCompraDiretaHabilitar", targetNamespace = "http://tempuri.org/")
        ArrayOfHabilitarCompraDiretaDTO lstCompraDiretaHabilitar);

}
