
package br.gov.sp.saobernardo.paradigma.ws.empresa;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Empresa", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Empresa.svc?wsdl")
public class Empresa
    extends Service
{

    private final static URL EMPRESA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.empresa.Empresa.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.empresa.Empresa.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Empresa.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Empresa.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EMPRESA_WSDL_LOCATION = url;
    }

    public Empresa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Empresa() {
        super(EMPRESA_WSDL_LOCATION, new QName("http://tempuri.org/", "Empresa"));
    }

    /**
     * 
     * @return
     *     returns IEmpresa
     */
    @WebEndpoint(name = "BasicHttpBinding_IEmpresa")
    public IEmpresa getBasicHttpBindingIEmpresa() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IEmpresa"), IEmpresa.class);
    }

}
