
package br.gov.sp.saobernardo.paradigma.ws.empresa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IEmpresa", targetNamespace = "http://tempuri.org/")
public interface IEmpresa {


    /**
     * 
     * @param lstEmpresa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarEmpresa", action = "http://tempuri.org/IEmpresa/ProcessarEmpresa")
    @WebResult(name = "ProcessarEmpresaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarEmpresa", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.ProcessarEmpresa")
    @ResponseWrapper(localName = "ProcessarEmpresaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.ProcessarEmpresaResponse")
    public RetornoDTO processarEmpresa(
        @WebParam(name = "lstEmpresa", targetNamespace = "http://tempuri.org/")
        ArrayOfEmpresaDTO lstEmpresa);

    /**
     * 
     * @param lstEmpresa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarEmpresaAvaliacao", action = "http://tempuri.org/IEmpresa/ProcessarEmpresaAvaliacao")
    @WebResult(name = "ProcessarEmpresaAvaliacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarEmpresaAvaliacao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.ProcessarEmpresaAvaliacao")
    @ResponseWrapper(localName = "ProcessarEmpresaAvaliacaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.ProcessarEmpresaAvaliacaoResponse")
    public RetornoDTO processarEmpresaAvaliacao(
        @WebParam(name = "lstEmpresa", targetNamespace = "http://tempuri.org/")
        ArrayOfEmpresaAvaliacaoDTO lstEmpresa);

    /**
     * 
     * @param lstEmpresaBloqueio
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarEmpresaBloqueio", action = "http://tempuri.org/IEmpresa/ProcessarEmpresaBloqueio")
    @WebResult(name = "ProcessarEmpresaBloqueioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarEmpresaBloqueio", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.ProcessarEmpresaBloqueio")
    @ResponseWrapper(localName = "ProcessarEmpresaBloqueioResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.ProcessarEmpresaBloqueioResponse")
    public RetornoDTO processarEmpresaBloqueio(
        @WebParam(name = "lstEmpresaBloqueio", targetNamespace = "http://tempuri.org/")
        ArrayOfEmpresaBloqueioDTO lstEmpresaBloqueio);

    /**
     * 
     * @param cnpj
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.EmpresaDTO
     */
    @WebMethod(operationName = "RetornarEmpresaPorCnpj", action = "http://tempuri.org/IEmpresa/RetornarEmpresaPorCnpj")
    @WebResult(name = "RetornarEmpresaPorCnpjResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaPorCnpj", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaPorCnpj")
    @ResponseWrapper(localName = "RetornarEmpresaPorCnpjResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaPorCnpjResponse")
    public EmpresaDTO retornarEmpresaPorCnpj(
        @WebParam(name = "Cnpj", targetNamespace = "http://tempuri.org/")
        String cnpj);

    /**
     * 
     * @param nCdEmpresa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.EmpresaDTO
     */
    @WebMethod(operationName = "RetornarEmpresaPorCodigoWBC", action = "http://tempuri.org/IEmpresa/RetornarEmpresaPorCodigoWBC")
    @WebResult(name = "RetornarEmpresaPorCodigoWBCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaPorCodigoWBC", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaPorCodigoWBC")
    @ResponseWrapper(localName = "RetornarEmpresaPorCodigoWBCResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaPorCodigoWBCResponse")
    public EmpresaDTO retornarEmpresaPorCodigoWBC(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        Long nCdEmpresa);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.ArrayOfEmpresaDTO
     */
    @WebMethod(operationName = "RetornarEmpresaVencedoraSemDePara", action = "http://tempuri.org/IEmpresa/RetornarEmpresaVencedoraSemDePara")
    @WebResult(name = "RetornarEmpresaVencedoraSemDeParaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaVencedoraSemDePara", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaVencedoraSemDePara")
    @ResponseWrapper(localName = "RetornarEmpresaVencedoraSemDeParaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaVencedoraSemDeParaResponse")
    public ArrayOfEmpresaDTO retornarEmpresaVencedoraSemDePara();

    /**
     * 
     * @param lstProcessoCotacaoDTO
     * @param nFlParticipa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.ArrayOfEmpresaDTO
     */
    @WebMethod(operationName = "RetornarEmpresaCotacao", action = "http://tempuri.org/IEmpresa/RetornarEmpresaCotacao")
    @WebResult(name = "RetornarEmpresaCotacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaCotacao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaCotacao")
    @ResponseWrapper(localName = "RetornarEmpresaCotacaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaCotacaoResponse")
    public ArrayOfEmpresaDTO retornarEmpresaCotacao(
        @WebParam(name = "lstProcessoCotacaoDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfProcessoCotacaoDTO lstProcessoCotacaoDTO,
        @WebParam(name = "nFlParticipa", targetNamespace = "http://tempuri.org/")
        Integer nFlParticipa);

    /**
     * 
     * @param lstProcessoLeilaoDTO
     * @param nFlParticipa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.ArrayOfEmpresaDTO
     */
    @WebMethod(operationName = "RetornarEmpresaLeilao", action = "http://tempuri.org/IEmpresa/RetornarEmpresaLeilao")
    @WebResult(name = "RetornarEmpresaLeilaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaLeilao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaLeilao")
    @ResponseWrapper(localName = "RetornarEmpresaLeilaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaLeilaoResponse")
    public ArrayOfEmpresaDTO retornarEmpresaLeilao(
        @WebParam(name = "lstProcessoLeilaoDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfProcessoLeilaoDTO lstProcessoLeilaoDTO,
        @WebParam(name = "nFlParticipa", targetNamespace = "http://tempuri.org/")
        Integer nFlParticipa);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.ArrayOfEmpresaDTO
     */
    @WebMethod(operationName = "RetornarEmpresaSemDePara", action = "http://tempuri.org/IEmpresa/RetornarEmpresaSemDePara")
    @WebResult(name = "RetornarEmpresaSemDeParaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaSemDePara", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaSemDePara")
    @ResponseWrapper(localName = "RetornarEmpresaSemDeParaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaSemDeParaResponse")
    public ArrayOfEmpresaDTO retornarEmpresaSemDePara();

    /**
     * 
     * @param sNrCnpj
     * @param lstUsuarioHomologador
     * @param sCdEmpresaErp
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.ArrayOfEmpresaDTO
     */
    @WebMethod(operationName = "RetornarEmpresaIntegracao", action = "http://tempuri.org/IEmpresa/RetornarEmpresaIntegracao")
    @WebResult(name = "RetornarEmpresaIntegracaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaIntegracao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaIntegracao")
    @ResponseWrapper(localName = "RetornarEmpresaIntegracaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaIntegracaoResponse")
    public ArrayOfEmpresaDTO retornarEmpresaIntegracao(
        @WebParam(name = "sCdEmpresaErp", targetNamespace = "http://tempuri.org/")
        String sCdEmpresaErp,
        @WebParam(name = "sNrCnpj", targetNamespace = "http://tempuri.org/")
        String sNrCnpj,
        @WebParam(name = "lstUsuarioHomologador", targetNamespace = "http://tempuri.org/")
        ArrayOfstring lstUsuarioHomologador);

    /**
     * 
     * @param lstLog
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.RetornoDTO
     */
    @WebMethod(operationName = "RetornarEmpresaIntegracaoFalha", action = "http://tempuri.org/IEmpresa/RetornarEmpresaIntegracaoFalha")
    @WebResult(name = "RetornarEmpresaIntegracaoFalhaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaIntegracaoFalha", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaIntegracaoFalha")
    @ResponseWrapper(localName = "RetornarEmpresaIntegracaoFalhaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaIntegracaoFalhaResponse")
    public RetornoDTO retornarEmpresaIntegracaoFalha(
        @WebParam(name = "lstLog", targetNamespace = "http://tempuri.org/")
        ArrayOfWbtLogCapaDTO lstLog);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.ArrayOfEmpresaDTO
     */
    @WebMethod(operationName = "RetornarEmpresaParticipante", action = "http://tempuri.org/IEmpresa/RetornarEmpresaParticipante")
    @WebResult(name = "RetornarEmpresaParticipanteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaParticipante", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaParticipante")
    @ResponseWrapper(localName = "RetornarEmpresaParticipanteResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaParticipanteResponse")
    public ArrayOfEmpresaDTO retornarEmpresaParticipante();

    /**
     * 
     * @param sCdEmpresaErp
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.EmpresaDTO
     */
    @WebMethod(operationName = "RetornarEmpresa", action = "http://tempuri.org/IEmpresa/RetornarEmpresa")
    @WebResult(name = "RetornarEmpresaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresa", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresa")
    @ResponseWrapper(localName = "RetornarEmpresaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaResponse")
    public EmpresaDTO retornarEmpresa(
        @WebParam(name = "sCdEmpresaErp", targetNamespace = "http://tempuri.org/")
        String sCdEmpresaErp);

    /**
     * 
     * @param nCdSituacao
     * @param nNrPagina
     * @param sNmEmpresa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.RetornoListaX003CEmpresaDTOX003E
     */
    @WebMethod(operationName = "RetornarEmpresaCompradoraPorNome", action = "http://tempuri.org/IEmpresa/RetornarEmpresaCompradoraPorNome")
    @WebResult(name = "RetornarEmpresaCompradoraPorNomeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaCompradoraPorNome", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaCompradoraPorNome")
    @ResponseWrapper(localName = "RetornarEmpresaCompradoraPorNomeResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaCompradoraPorNomeResponse")
    public RetornoListaX003CEmpresaDTOX003E retornarEmpresaCompradoraPorNome(
        @WebParam(name = "sNmEmpresa", targetNamespace = "http://tempuri.org/")
        String sNmEmpresa,
        @WebParam(name = "nCdSituacao", targetNamespace = "http://tempuri.org/")
        Integer nCdSituacao,
        @WebParam(name = "nNrPagina", targetNamespace = "http://tempuri.org/")
        Integer nNrPagina);

    /**
     * 
     * @param sNrCnpj
     * @param sCdEmpresaErp
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.EmpresaDTO
     */
    @WebMethod(operationName = "RetornarEmpresaVerificacaoDepara", action = "http://tempuri.org/IEmpresa/RetornarEmpresaVerificacaoDepara")
    @WebResult(name = "RetornarEmpresaVerificacaoDeparaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarEmpresaVerificacaoDepara", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaVerificacaoDepara")
    @ResponseWrapper(localName = "RetornarEmpresaVerificacaoDeparaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarEmpresaVerificacaoDeparaResponse")
    public EmpresaDTO retornarEmpresaVerificacaoDepara(
        @WebParam(name = "sCdEmpresaErp", targetNamespace = "http://tempuri.org/")
        String sCdEmpresaErp,
        @WebParam(name = "sNrCnpj", targetNamespace = "http://tempuri.org/")
        String sNrCnpj);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.ArrayOfFornecedorDTO
     */
    @WebMethod(operationName = "RetornarFornecedorIntegracao", action = "http://tempuri.org/IEmpresa/RetornarFornecedorIntegracao")
    @WebResult(name = "RetornarFornecedorIntegracaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarFornecedorIntegracao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarFornecedorIntegracao")
    @ResponseWrapper(localName = "RetornarFornecedorIntegracaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.RetornarFornecedorIntegracaoResponse")
    public ArrayOfFornecedorDTO retornarFornecedorIntegracao();

    /**
     * 
     * @param sNrCnpj
     * @param nCdEmpresa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresa.RetornoDTO
     */
    @WebMethod(operationName = "CriarDeParaFornecedorCasoNaoExista", action = "http://tempuri.org/IEmpresa/CriarDeParaFornecedorCasoNaoExista")
    @WebResult(name = "CriarDeParaFornecedorCasoNaoExistaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CriarDeParaFornecedorCasoNaoExista", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.CriarDeParaFornecedorCasoNaoExista")
    @ResponseWrapper(localName = "CriarDeParaFornecedorCasoNaoExistaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresa.CriarDeParaFornecedorCasoNaoExistaResponse")
    public RetornoDTO criarDeParaFornecedorCasoNaoExista(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        Long nCdEmpresa,
        @WebParam(name = "sNrCnpj", targetNamespace = "http://tempuri.org/")
        String sNrCnpj);

}
