
package br.gov.sp.saobernardo.paradigma.ws.documento;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Documento", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/Documento.svc?wsdl")
public class Documento
    extends Service
{

    private final static URL DOCUMENTO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.documento.Documento.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.documento.Documento.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/Documento.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/Documento.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCUMENTO_WSDL_LOCATION = url;
    }

    public Documento(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Documento() {
        super(DOCUMENTO_WSDL_LOCATION, new QName("http://tempuri.org/", "Documento"));
    }

    /**
     * 
     * @return
     *     returns IDocumento
     */
    @WebEndpoint(name = "BasicHttpBinding_IDocumento")
    public IDocumento getBasicHttpBindingIDocumento() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IDocumento"), IDocumento.class);
    }

}
