
package br.gov.sp.saobernardo.paradigma.ws.wbtdepara;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IWbtDePara", targetNamespace = "http://tempuri.org/")
public interface IWbtDePara {


    /**
     * 
     * @param enumTipoDocumento
     * @param oWbtDeParaDTO
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornarDeParaWbc", action = "http://tempuri.org/IWbtDePara/RetornarDeParaWbc")
    @WebResult(name = "RetornarDeParaWbcResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarDeParaWbc", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtdepara.RetornarDeParaWbc")
    @ResponseWrapper(localName = "RetornarDeParaWbcResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtdepara.RetornarDeParaWbcResponse")
    public String retornarDeParaWbc(
        @WebParam(name = "enumTipoDocumento", targetNamespace = "http://tempuri.org/")
        EnumTipoDocumento enumTipoDocumento,
        @WebParam(name = "oWbtDeParaDTO", targetNamespace = "http://tempuri.org/")
        WbtDeParaDTO oWbtDeParaDTO);

    /**
     * 
     * @param enumTipoDocumento
     * @param sCdItemWbc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetornarDeParaErp", action = "http://tempuri.org/IWbtDePara/RetornarDeParaErp")
    @WebResult(name = "RetornarDeParaErpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarDeParaErp", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtdepara.RetornarDeParaErp")
    @ResponseWrapper(localName = "RetornarDeParaErpResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtdepara.RetornarDeParaErpResponse")
    public String retornarDeParaErp(
        @WebParam(name = "enumTipoDocumento", targetNamespace = "http://tempuri.org/")
        EnumTipoDocumento enumTipoDocumento,
        @WebParam(name = "sCdItemWbc", targetNamespace = "http://tempuri.org/")
        String sCdItemWbc);

    /**
     * 
     * @param enumTipoDocumento
     * @param sCdItemWbc
     * @param sCdItemEmpresa
     */
    @WebMethod(operationName = "Salvar", action = "http://tempuri.org/IWbtDePara/Salvar")
    @RequestWrapper(localName = "Salvar", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtdepara.Salvar")
    @ResponseWrapper(localName = "SalvarResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtdepara.SalvarResponse")
    public void salvar(
        @WebParam(name = "enumTipoDocumento", targetNamespace = "http://tempuri.org/")
        EnumTipoDocumento enumTipoDocumento,
        @WebParam(name = "sCdItemWbc", targetNamespace = "http://tempuri.org/")
        String sCdItemWbc,
        @WebParam(name = "sCdItemEmpresa", targetNamespace = "http://tempuri.org/")
        String sCdItemEmpresa);

    /**
     * 
     * @param sCdEmpresa
     * @param enumTipoDocumento
     * @param sCdItemWbc
     * @param sCdItemEmpresa
     */
    @WebMethod(operationName = "SalvarPorEmpresa", action = "http://tempuri.org/IWbtDePara/SalvarPorEmpresa")
    @RequestWrapper(localName = "SalvarPorEmpresa", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtdepara.SalvarPorEmpresa")
    @ResponseWrapper(localName = "SalvarPorEmpresaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtdepara.SalvarPorEmpresaResponse")
    public void salvarPorEmpresa(
        @WebParam(name = "enumTipoDocumento", targetNamespace = "http://tempuri.org/")
        EnumTipoDocumento enumTipoDocumento,
        @WebParam(name = "sCdEmpresa", targetNamespace = "http://tempuri.org/")
        String sCdEmpresa,
        @WebParam(name = "sCdItemWbc", targetNamespace = "http://tempuri.org/")
        String sCdItemWbc,
        @WebParam(name = "sCdItemEmpresa", targetNamespace = "http://tempuri.org/")
        String sCdItemEmpresa);

    /**
     * 
     * @param sCdDePara
     * @param sCdEmpresa
     * @param enumTipoDocumento
     * @param sCdMultiEmpresa
     */
    @WebMethod(operationName = "GerarDeParaMultiploPorEmpresa", action = "http://tempuri.org/IWbtDePara/GerarDeParaMultiploPorEmpresa")
    @RequestWrapper(localName = "GerarDeParaMultiploPorEmpresa", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtdepara.GerarDeParaMultiploPorEmpresa")
    @ResponseWrapper(localName = "GerarDeParaMultiploPorEmpresaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wbtdepara.GerarDeParaMultiploPorEmpresaResponse")
    public void gerarDeParaMultiploPorEmpresa(
        @WebParam(name = "enumTipoDocumento", targetNamespace = "http://tempuri.org/")
        EnumTipoDocumento enumTipoDocumento,
        @WebParam(name = "sCdDePara", targetNamespace = "http://tempuri.org/")
        String sCdDePara,
        @WebParam(name = "sCdEmpresa", targetNamespace = "http://tempuri.org/")
        String sCdEmpresa,
        @WebParam(name = "sCdMultiEmpresa", targetNamespace = "http://tempuri.org/")
        String sCdMultiEmpresa);

}
