
package br.gov.sp.saobernardo.paradigma.ws.wbtdepara;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WbtDePara", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/WbtDePara.svc?wsdl")
public class WbtDePara
    extends Service
{

    private final static URL WBTDEPARA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.wbtdepara.WbtDePara.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.wbtdepara.WbtDePara.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/WbtDePara.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/WbtDePara.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WBTDEPARA_WSDL_LOCATION = url;
    }

    public WbtDePara(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WbtDePara() {
        super(WBTDEPARA_WSDL_LOCATION, new QName("http://tempuri.org/", "WbtDePara"));
    }

    /**
     * 
     * @return
     *     returns IWbtDePara
     */
    @WebEndpoint(name = "BasicHttpBinding_IWbtDePara")
    public IWbtDePara getBasicHttpBindingIWbtDePara() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWbtDePara"), IWbtDePara.class);
    }

}
