
package br.gov.sp.saobernardo.paradigma.ws.unidademedida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IUnidadeMedida", targetNamespace = "http://tempuri.org/")
public interface IUnidadeMedida {


    /**
     * 
     * @param lstUnidadeMedida
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.unidademedida.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarUnidadeMedida", action = "http://tempuri.org/IUnidadeMedida/ProcessarUnidadeMedida")
    @WebResult(name = "ProcessarUnidadeMedidaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarUnidadeMedida", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.unidademedida.ProcessarUnidadeMedida")
    @ResponseWrapper(localName = "ProcessarUnidadeMedidaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.unidademedida.ProcessarUnidadeMedidaResponse")
    public RetornoDTO processarUnidadeMedida(
        @WebParam(name = "lstUnidadeMedida", targetNamespace = "http://tempuri.org/")
        ArrayOfUnidadeMedidaDTO lstUnidadeMedida);

    /**
     * 
     * @param sCdUnidadeMedidaErp
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.unidademedida.UnidadeMedidaDTO
     */
    @WebMethod(operationName = "RetornarUnidadeMedida", action = "http://tempuri.org/IUnidadeMedida/RetornarUnidadeMedida")
    @WebResult(name = "RetornarUnidadeMedidaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarUnidadeMedida", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.unidademedida.RetornarUnidadeMedida")
    @ResponseWrapper(localName = "RetornarUnidadeMedidaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.unidademedida.RetornarUnidadeMedidaResponse")
    public UnidadeMedidaDTO retornarUnidadeMedida(
        @WebParam(name = "sCdUnidadeMedidaErp", targetNamespace = "http://tempuri.org/")
        String sCdUnidadeMedidaErp);

    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.unidademedida.RetornoListaX003CUnidadeMedidaDTOX003E
     */
    @WebMethod(operationName = "RetornarUnidadeMedidaAtiva", action = "http://tempuri.org/IUnidadeMedida/RetornarUnidadeMedidaAtiva")
    @WebResult(name = "RetornarUnidadeMedidaAtivaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarUnidadeMedidaAtiva", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.unidademedida.RetornarUnidadeMedidaAtiva")
    @ResponseWrapper(localName = "RetornarUnidadeMedidaAtivaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.unidademedida.RetornarUnidadeMedidaAtivaResponse")
    public RetornoListaX003CUnidadeMedidaDTOX003E retornarUnidadeMedidaAtiva();

}
