
package br.gov.sp.saobernardo.paradigma.ws.unidademedida;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "UnidadeMedida", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/UnidadeMedida.svc?wsdl")
public class UnidadeMedida
    extends Service
{

    private final static URL UNIDADEMEDIDA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.unidademedida.UnidadeMedida.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.unidademedida.UnidadeMedida.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/UnidadeMedida.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/UnidadeMedida.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        UNIDADEMEDIDA_WSDL_LOCATION = url;
    }

    public UnidadeMedida(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnidadeMedida() {
        super(UNIDADEMEDIDA_WSDL_LOCATION, new QName("http://tempuri.org/", "UnidadeMedida"));
    }

    /**
     * 
     * @return
     *     returns IUnidadeMedida
     */
    @WebEndpoint(name = "BasicHttpBinding_IUnidadeMedida")
    public IUnidadeMedida getBasicHttpBindingIUnidadeMedida() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IUnidadeMedida"), IUnidadeMedida.class);
    }

}
