
package br.gov.sp.saobernardo.paradigma.ws.condicaopagamento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ICondicaoPagamento", targetNamespace = "http://tempuri.org/")
public interface ICondicaoPagamento {


    /**
     * 
     * @param lstCondicaoPagamento
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.condicaopagamento.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarCondicaoPagamento", action = "http://tempuri.org/ICondicaoPagamento/ProcessarCondicaoPagamento")
    @WebResult(name = "ProcessarCondicaoPagamentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarCondicaoPagamento", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.condicaopagamento.ProcessarCondicaoPagamento")
    @ResponseWrapper(localName = "ProcessarCondicaoPagamentoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.condicaopagamento.ProcessarCondicaoPagamentoResponse")
    public RetornoDTO processarCondicaoPagamento(
        @WebParam(name = "lstCondicaoPagamento", targetNamespace = "http://tempuri.org/")
        ArrayOfCondicaoPagamentoDTO lstCondicaoPagamento);

    /**
     * 
     * @param sCdCondicaoPagamentoErp
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.condicaopagamento.CondicaoPagamentoDTO
     */
    @WebMethod(operationName = "RetornarCondicaoPagamento", action = "http://tempuri.org/ICondicaoPagamento/RetornarCondicaoPagamento")
    @WebResult(name = "RetornarCondicaoPagamentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarCondicaoPagamento", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.condicaopagamento.RetornarCondicaoPagamento")
    @ResponseWrapper(localName = "RetornarCondicaoPagamentoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.condicaopagamento.RetornarCondicaoPagamentoResponse")
    public CondicaoPagamentoDTO retornarCondicaoPagamento(
        @WebParam(name = "sCdCondicaoPagamentoErp", targetNamespace = "http://tempuri.org/")
        String sCdCondicaoPagamentoErp);

}
