
package br.gov.sp.saobernardo.paradigma.ws.categoria;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "Categoria", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/D:/workspace/PARADIGMA_WEBSERVICE_projeto/gerador_ws/Categoria.wsdl")
public class Categoria
    extends Service
{

    private final static URL CATEGORIA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.categoria.Categoria.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.categoria.Categoria.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/workspace/PARADIGMA_WEBSERVICE_projeto/gerador_ws/Categoria.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/workspace/PARADIGMA_WEBSERVICE_projeto/gerador_ws/Categoria.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CATEGORIA_WSDL_LOCATION = url;
    }

    public Categoria(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Categoria() {
        super(CATEGORIA_WSDL_LOCATION, new QName("http://tempuri.org/", "Categoria"));
    }

    /**
     * 
     * @return
     *     returns ICategoria
     */
    @WebEndpoint(name = "BasicHttpBinding_ICategoria")
    public ICategoria getBasicHttpBindingICategoria() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICategoria"), ICategoria.class);
    }

}
