
package br.gov.sp.saobernardo.paradigma.ws.categoria;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ICategoria", targetNamespace = "http://tempuri.org/")
public interface ICategoria {


    /**
     * 
     * @param lstCategoria
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.categoria.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarCategoriaProduto", action = "http://tempuri.org/ICategoria/ProcessarCategoriaProduto")
    @WebResult(name = "ProcessarCategoriaProdutoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarCategoriaProduto", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.categoria.ProcessarCategoriaProduto")
    @ResponseWrapper(localName = "ProcessarCategoriaProdutoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.categoria.ProcessarCategoriaProdutoResponse")
    public RetornoDTO processarCategoriaProduto(
        @WebParam(name = "lstCategoria", targetNamespace = "http://tempuri.org/")
        ArrayOfCategoriaDTO lstCategoria);

    /**
     * 
     * @param sCdCategoriaProdutpERP
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.categoria.CategoriaDTO
     */
    @WebMethod(operationName = "RetornarCategoriaProduto", action = "http://tempuri.org/ICategoria/RetornarCategoriaProduto")
    @WebResult(name = "RetornarCategoriaProdutoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarCategoriaProduto", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.categoria.RetornarCategoriaProduto")
    @ResponseWrapper(localName = "RetornarCategoriaProdutoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.categoria.RetornarCategoriaProdutoResponse")
    public CategoriaDTO retornarCategoriaProduto(
        @WebParam(name = "sCdCategoriaProdutpERP", targetNamespace = "http://tempuri.org/")
        String sCdCategoriaProdutpERP);

}
