
package br.gov.sp.saobernardo.paradigma.ws.produto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IProduto", targetNamespace = "http://tempuri.org/")
public interface IProduto {


    /**
     * 
     * @param lstProduto
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produto.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarProduto", action = "http://tempuri.org/IProduto/ProcessarProduto")
    @WebResult(name = "ProcessarProdutoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarProduto", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.ProcessarProduto")
    @ResponseWrapper(localName = "ProcessarProdutoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.ProcessarProdutoResponse")
    public RetornoDTO processarProduto(
        @WebParam(name = "lstProduto", targetNamespace = "http://tempuri.org/")
        ArrayOfProdutoDTO lstProduto);

    /**
     * 
     * @param sCdProdutoErp
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produto.ProdutoDTO
     */
    @WebMethod(operationName = "RetornarProduto", action = "http://tempuri.org/IProduto/RetornarProduto")
    @WebResult(name = "RetornarProdutoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarProduto", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProduto")
    @ResponseWrapper(localName = "RetornarProdutoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoResponse")
    public ProdutoDTO retornarProduto(
        @WebParam(name = "sCdProdutoErp", targetNamespace = "http://tempuri.org/")
        String sCdProdutoErp);

    /**
     * 
     * @param sCdClasse
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produto.ArrayOfProdutoDTO
     */
    @WebMethod(operationName = "RetornarProdutoPorCategoria", action = "http://tempuri.org/IProduto/RetornarProdutoPorCategoria")
    @WebResult(name = "RetornarProdutoPorCategoriaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarProdutoPorCategoria", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoPorCategoria")
    @ResponseWrapper(localName = "RetornarProdutoPorCategoriaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoPorCategoriaResponse")
    public ArrayOfProdutoDTO retornarProdutoPorCategoria(
        @WebParam(name = "sCdClasse", targetNamespace = "http://tempuri.org/")
        String sCdClasse);

    /**
     * 
     * @param sCdEmpresa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produto.RetornoListaX003CProdutoDTOX003E
     */
    @WebMethod(operationName = "RetornarProdutoSemDePara", action = "http://tempuri.org/IProduto/RetornarProdutoSemDePara")
    @WebResult(name = "RetornarProdutoSemDeParaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarProdutoSemDePara", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoSemDePara")
    @ResponseWrapper(localName = "RetornarProdutoSemDeParaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoSemDeParaResponse")
    public RetornoListaX003CProdutoDTOX003E retornarProdutoSemDePara(
        @WebParam(name = "sCdEmpresa", targetNamespace = "http://tempuri.org/")
        String sCdEmpresa);

    /**
     * 
     * @param nNrPagina
     * @param sCdProduto
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produto.RetornoListaX003CProdutoDTOX003E
     */
    @WebMethod(operationName = "RetornarProdutoPorCodigo", action = "http://tempuri.org/IProduto/RetornarProdutoPorCodigo")
    @WebResult(name = "RetornarProdutoPorCodigoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarProdutoPorCodigo", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoPorCodigo")
    @ResponseWrapper(localName = "RetornarProdutoPorCodigoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoPorCodigoResponse")
    public RetornoListaX003CProdutoDTOX003E retornarProdutoPorCodigo(
        @WebParam(name = "sCdProduto", targetNamespace = "http://tempuri.org/")
        String sCdProduto,
        @WebParam(name = "nNrPagina", targetNamespace = "http://tempuri.org/")
        Integer nNrPagina);

    /**
     * 
     * @param sStProduto
     * @param sDsProduto
     * @param nNrPagina
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produto.RetornoListaX003CProdutoDTOX003E
     */
    @WebMethod(operationName = "RetornarProdutoPorDescricao", action = "http://tempuri.org/IProduto/RetornarProdutoPorDescricao")
    @WebResult(name = "RetornarProdutoPorDescricaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarProdutoPorDescricao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoPorDescricao")
    @ResponseWrapper(localName = "RetornarProdutoPorDescricaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoPorDescricaoResponse")
    public RetornoListaX003CProdutoDTOX003E retornarProdutoPorDescricao(
        @WebParam(name = "sDsProduto", targetNamespace = "http://tempuri.org/")
        String sDsProduto,
        @WebParam(name = "sStProduto", targetNamespace = "http://tempuri.org/")
        String sStProduto,
        @WebParam(name = "nNrPagina", targetNamespace = "http://tempuri.org/")
        Integer nNrPagina);

    /**
     * 
     * @param sStProduto
     * @param sDsProduto
     * @param nNrPagina
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produto.RetornoListaX003CProdutoDTOX003E
     */
    @WebMethod(operationName = "RetornarProdutoEmContratoPorDescricao", action = "http://tempuri.org/IProduto/RetornarProdutoEmContratoPorDescricao")
    @WebResult(name = "RetornarProdutoEmContratoPorDescricaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarProdutoEmContratoPorDescricao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoEmContratoPorDescricao")
    @ResponseWrapper(localName = "RetornarProdutoEmContratoPorDescricaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.RetornarProdutoEmContratoPorDescricaoResponse")
    public RetornoListaX003CProdutoDTOX003E retornarProdutoEmContratoPorDescricao(
        @WebParam(name = "sDsProduto", targetNamespace = "http://tempuri.org/")
        String sDsProduto,
        @WebParam(name = "sStProduto", targetNamespace = "http://tempuri.org/")
        String sStProduto,
        @WebParam(name = "nNrPagina", targetNamespace = "http://tempuri.org/")
        Integer nNrPagina);

    /**
     * 
     * @param lstProdutoHpf
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produto.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarDataProdutoHpf", action = "http://tempuri.org/IProduto/ProcessarDataProdutoHpf")
    @WebResult(name = "ProcessarDataProdutoHpfResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarDataProdutoHpf", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.ProcessarDataProdutoHpf")
    @ResponseWrapper(localName = "ProcessarDataProdutoHpfResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.ProcessarDataProdutoHpfResponse")
    public RetornoDTO processarDataProdutoHpf(
        @WebParam(name = "lstProdutoHpf", targetNamespace = "http://tempuri.org/")
        ArrayOfProdutoHpfDTO lstProdutoHpf);

    /**
     * 
     * @param sCdProdutoWBC
     * @param sCdProduto
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.produto.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarProdutoCodigoDePara", action = "http://tempuri.org/IProduto/ProcessarProdutoCodigoDePara")
    @WebResult(name = "ProcessarProdutoCodigoDeParaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarProdutoCodigoDePara", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.ProcessarProdutoCodigoDePara")
    @ResponseWrapper(localName = "ProcessarProdutoCodigoDeParaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.produto.ProcessarProdutoCodigoDeParaResponse")
    public RetornoDTO processarProdutoCodigoDePara(
        @WebParam(name = "sCdProduto", targetNamespace = "http://tempuri.org/")
        String sCdProduto,
        @WebParam(name = "sCdProdutoWBC", targetNamespace = "http://tempuri.org/")
        String sCdProdutoWBC);

}
