
package br.gov.sp.saobernardo.paradigma.ws.leilao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ILeilao", targetNamespace = "http://tempuri.org/")
public interface ILeilao {


    /**
     * 
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.leilao.ArrayOfLeilaoDTO
     */
    @WebMethod(operationName = "RetornarLeilao", action = "http://tempuri.org/ILeilao/RetornarLeilao")
    @WebResult(name = "RetornarLeilaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarLeilao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.leilao.RetornarLeilao")
    @ResponseWrapper(localName = "RetornarLeilaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.leilao.RetornarLeilaoResponse")
    public ArrayOfLeilaoDTO retornarLeilao();

    /**
     * 
     * @param lstLeilao
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.leilao.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarLeilao", action = "http://tempuri.org/ILeilao/ProcessarLeilao")
    @WebResult(name = "ProcessarLeilaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarLeilao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.leilao.ProcessarLeilao")
    @ResponseWrapper(localName = "ProcessarLeilaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.leilao.ProcessarLeilaoResponse")
    public RetornoDTO processarLeilao(
        @WebParam(name = "lstLeilao", targetNamespace = "http://tempuri.org/")
        ArrayOfLeilaoDTO lstLeilao);

    /**
     * 
     * @param nFlParticipa
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.leilao.ArrayOfProcessoLeilaoDTO
     */
    @WebMethod(operationName = "RetornarLeilaoComEmpresaSemDePara", action = "http://tempuri.org/ILeilao/RetornarLeilaoComEmpresaSemDePara")
    @WebResult(name = "RetornarLeilaoComEmpresaSemDeParaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarLeilaoComEmpresaSemDePara", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.leilao.RetornarLeilaoComEmpresaSemDePara")
    @ResponseWrapper(localName = "RetornarLeilaoComEmpresaSemDeParaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.leilao.RetornarLeilaoComEmpresaSemDeParaResponse")
    public ArrayOfProcessoLeilaoDTO retornarLeilaoComEmpresaSemDePara(
        @WebParam(name = "nFlParticipa", targetNamespace = "http://tempuri.org/")
        Integer nFlParticipa);

    /**
     * 
     * @param lstConfirmacaoNegociacaoDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.leilao.RetornoDTO
     */
    @WebMethod(operationName = "HabilitarRetornarLeilao", action = "http://tempuri.org/ILeilao/HabilitarRetornarLeilao")
    @WebResult(name = "HabilitarRetornarLeilaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HabilitarRetornarLeilao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.leilao.HabilitarRetornarLeilao")
    @ResponseWrapper(localName = "HabilitarRetornarLeilaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.leilao.HabilitarRetornarLeilaoResponse")
    public RetornoDTO habilitarRetornarLeilao(
        @WebParam(name = "lstConfirmacaoNegociacaoDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfConfirmacaoNegociacaoDTO lstConfirmacaoNegociacaoDTO);

}
