
package br.gov.sp.saobernardo.paradigma.ws.empresabanco;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IEmpresaBanco", targetNamespace = "http://tempuri.org/")
public interface IEmpresaBanco {


    /**
     * 
     * @param lstEmpresaBanco
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.empresabanco.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarContaBancaria", action = "http://tempuri.org/IEmpresaBanco/ProcessarContaBancaria")
    @WebResult(name = "ProcessarContaBancariaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarContaBancaria", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresabanco.ProcessarContaBancaria")
    @ResponseWrapper(localName = "ProcessarContaBancariaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.empresabanco.ProcessarContaBancariaResponse")
    public RetornoDTO processarContaBancaria(
        @WebParam(name = "lstEmpresaBanco", targetNamespace = "http://tempuri.org/")
        ArrayOfEmpresaBancoDTO lstEmpresaBanco);

}
