
package br.gov.sp.saobernardo.paradigma.ws.wfatividade;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IWfAtividade", targetNamespace = "http://tempuri.org/")
public interface IWfAtividade {


    /**
     * 
     * @param lstCdObjeto
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.wfatividade.RetornoListaX003CWfAtividadeAprovacaoDTOX003E
     */
    @WebMethod(operationName = "RetornarAtividadeAprovacao", action = "http://tempuri.org/IWfAtividade/RetornarAtividadeAprovacao")
    @WebResult(name = "RetornarAtividadeAprovacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetornarAtividadeAprovacao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfatividade.RetornarAtividadeAprovacao")
    @ResponseWrapper(localName = "RetornarAtividadeAprovacaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfatividade.RetornarAtividadeAprovacaoResponse")
    public RetornoListaX003CWfAtividadeAprovacaoDTOX003E retornarAtividadeAprovacao(
        @WebParam(name = "lstCdObjeto", targetNamespace = "http://tempuri.org/")
        ArrayOflong lstCdObjeto);

    /**
     * 
     * @param lstCdAtividade
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.wfatividade.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarAtividadeRecebida", action = "http://tempuri.org/IWfAtividade/ProcessarAtividadeRecebida")
    @WebResult(name = "ProcessarAtividadeRecebidaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarAtividadeRecebida", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfatividade.ProcessarAtividadeRecebida")
    @ResponseWrapper(localName = "ProcessarAtividadeRecebidaResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfatividade.ProcessarAtividadeRecebidaResponse")
    public RetornoDTO processarAtividadeRecebida(
        @WebParam(name = "lstCdAtividade", targetNamespace = "http://tempuri.org/")
        ArrayOflong lstCdAtividade);

    /**
     * 
     * @param lstWfAtividadeDelegarDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.wfatividade.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarAtividadeDelegar", action = "http://tempuri.org/IWfAtividade/ProcessarAtividadeDelegar")
    @WebResult(name = "ProcessarAtividadeDelegarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarAtividadeDelegar", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfatividade.ProcessarAtividadeDelegar")
    @ResponseWrapper(localName = "ProcessarAtividadeDelegarResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfatividade.ProcessarAtividadeDelegarResponse")
    public RetornoDTO processarAtividadeDelegar(
        @WebParam(name = "lstWfAtividadeDelegarDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfWfAtividadeDelegarDTO lstWfAtividadeDelegarDTO);

    /**
     * 
     * @param lstWfAtividadeAprovacaoResultadoDTO
     * @return
     *     returns br.gov.sp.saobernardo.paradigma.ws.wfatividade.RetornoDTO
     */
    @WebMethod(operationName = "ProcessarAtividadeAprovacao", action = "http://tempuri.org/IWfAtividade/ProcessarAtividadeAprovacao")
    @WebResult(name = "ProcessarAtividadeAprovacaoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessarAtividadeAprovacao", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfatividade.ProcessarAtividadeAprovacao")
    @ResponseWrapper(localName = "ProcessarAtividadeAprovacaoResponse", targetNamespace = "http://tempuri.org/", className = "br.gov.sp.saobernardo.paradigma.ws.wfatividade.ProcessarAtividadeAprovacaoResponse")
    public RetornoDTO processarAtividadeAprovacao(
        @WebParam(name = "lstWfAtividadeAprovacaoResultadoDTO", targetNamespace = "http://tempuri.org/")
        ArrayOfWfAtividadeAprovacaoResultadoDTO lstWfAtividadeAprovacaoResultadoDTO);

}
