
package br.gov.sp.saobernardo.paradigma.ws.wfatividade;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WfAtividade", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://comprashmg.pmsbc.gov.br/Services/WfAtividade.svc?wsdl")
public class WfAtividade
    extends Service
{

    private final static URL WFATIVIDADE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.gov.sp.saobernardo.paradigma.ws.wfatividade.WfAtividade.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.gov.sp.saobernardo.paradigma.ws.wfatividade.WfAtividade.class.getResource(".");
            url = new URL(baseUrl, "http://comprashmg.pmsbc.gov.br/Services/WfAtividade.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://comprashmg.pmsbc.gov.br/Services/WfAtividade.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WFATIVIDADE_WSDL_LOCATION = url;
    }

    public WfAtividade(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WfAtividade() {
        super(WFATIVIDADE_WSDL_LOCATION, new QName("http://tempuri.org/", "WfAtividade"));
    }

    /**
     * 
     * @return
     *     returns IWfAtividade
     */
    @WebEndpoint(name = "BasicHttpBinding_IWfAtividade")
    public IWfAtividade getBasicHttpBindingIWfAtividade() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWfAtividade"), IWfAtividade.class);
    }

}
